// ============================================================
// Certus — Series 7 question bank (blueprint-weighted)
//
// Written AFTER the readings that teach this material. A concept audit
// against the FINRA outline found 29 testable Series 7 concepts taught
// nowhere in our readings — settlement mechanics, cold-calling rules,
// retirement accounts, bond counsel and advance refunding, option
// assignment and position limits. Those readings were added first
// (series7-wave3.ts, series7.ts, series7-extra.ts) and this file tests
// only what they now cover.
//
// WEIGHTING: FINRA's four functions are 7 / 9 / 73 / 11 percent. F3
// ("Provides Information, Makes Recommendations") is nearly three
// quarters of the exam, so it gets nearly three quarters of the bank.
// The previous Series 7 bank had a flat 11 questions per chapter topic,
// which ignored the weighting entirely.
//
// NOTE: literal strings only for topicId/topicName — the audit,
// coverage, verifier and alignment scripts parse this file as TEXT.
// A shared constant resolves to nothing and the questions become
// invisible to every quality gate.
// ============================================================

import { Question } from "./types";

export const series7Questions: Question[] = [
  { id: "s7q-f1-001", examSlug: "series-7", topicId: "f1-business", topicName: "Seeking Business", difficulty: 1,
    stem: "Cold calls may be placed between:",
    choices: ["8:00 a.m. and 9:00 p.m. in the called party's time zone", "9:00 a.m. and 5:00 p.m. in the caller's time zone", "8:00 a.m. and 9:00 p.m. in the caller's time zone", "Any hours, if the firm approves"],
    answerIndex: 0,
    explanation: "The window is measured where the RECIPIENT is, not the caller. A New York representative dialling California at 8:30 a.m. Eastern is calling at 5:30 a.m. Pacific — a violation despite being inside the window locally." },
  { id: "s7q-f1-002", examSlug: "series-7", topicId: "f1-business", topicName: "Seeking Business", difficulty: 2,
    stem: "A person asks to be removed from a firm's call list. The request:",
    choices: ["Expires after one year", "Applies indefinitely, regardless of any relationship", "Applies only if they are not a customer", "May be overridden by a principal"],
    answerIndex: 1,
    explanation: "A removal request must be honoured promptly and survives indefinitely. Existing-customer and prior-consent exceptions govern whether a call may be made in the first place, but once someone asks to be removed the firm must comply." },
  { id: "s7q-f1-003", examSlug: "series-7", topicId: "f1-business", topicName: "Seeking Business", difficulty: 2,
    stem: "Which cold call is permitted outside the Do-Not-Call restrictions?",
    choices: ["A call to a name from a purchased list", "A call at 7:00 a.m. local time", "A call to an existing customer", "A call to someone on the national registry"],
    answerIndex: 2,
    explanation: "Existing customers, prior written consent, and an established business relationship all fall outside the restrictions. Purchased lists, out-of-hours calls and registry-listed strangers do not." },
  { id: "s7q-f1-004", examSlug: "series-7", topicId: "f1-business", topicName: "Seeking Business", difficulty: 2,
    stem: "Slides used at an investment seminar are treated as:",
    choices: ["Internal material", "Correspondence", "Exempt from review", "A retail communication requiring principal approval"],
    answerIndex: 3,
    explanation: "A seminar is a communication with the public, so scripts, slides and handouts require principal approval and must be fair, balanced and not misleading. Extemporaneous remarks are not pre-approved but the representative remains responsible for them." },
  { id: "s7q-f1-005", examSlug: "series-7", topicId: "f1-business", topicName: "Seeking Business", difficulty: 2,
    stem: "A piece sent to 40 retail investors in one month is:",
    choices: ["A retail communication", "Correspondence", "An institutional communication", "Exempt"],
    answerIndex: 0,
    explanation: "More than 25 retail investors within 30 calendar days makes it a retail communication requiring principal approval BEFORE first use. Twenty-five or fewer would be correspondence, reviewed under firm procedures." },
  { id: "s7q-f1-006", examSlug: "series-7", topicId: "f1-business", topicName: "Seeking Business", difficulty: 2,
    stem: "A tombstone advertisement may include:",
    choices: ["A recommendation to buy", "The issuer, the security, and where to obtain a prospectus", "A projected return", "An SEC endorsement"],
    answerIndex: 1,
    explanation: "Tombstones are limited to identifying facts and may run during the cooling-off period. Recommendations, projections and any claim of SEC approval are all prohibited — the SEC never endorses a security." },
  { id: "s7q-f1-007", examSlug: "series-7", topicId: "f1-business", topicName: "Seeking Business", difficulty: 1,
    stem: "A cold caller must disclose:",
    choices: ["Their compensation", "The firm's net capital", "Their name, the firm, and a contact number or address", "Their exam scores"],
    answerIndex: 2,
    explanation: "Identification is mandatory: the caller's name, the firm's name, and a telephone number or address at which the firm can be reached. Compensation and financial details are not required on the call." },
  { id: "s7q-f1-008", examSlug: "series-7", topicId: "f1-business", topicName: "Seeking Business", difficulty: 3,
    stem: "A representative wants to email a research piece to 30 retail clients and 5 institutions. The retail portion is:",
    choices: ["Correspondence", "Institutional material", "Exempt from the count", "A retail communication needing pre-approval"],
    answerIndex: 3,
    explanation: "The retail count is what governs: 30 exceeds 25 within 30 days, so pre-approval is required. Institutional recipients are counted separately and their copy needs review procedures but no pre-approval." },
  { id: "s7q-f2-001", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opening Accounts", difficulty: 1,
    stem: "A corporate account requires:",
    choices: ["A corporate resolution naming authorised traders", "Only a principal's signature", "A margin agreement", "A power of attorney"],
    answerIndex: 0,
    explanation: "The resolution identifies who may act for the entity. A partnership account requires the partnership agreement for the same purpose — the firm must know whose instructions are binding." },
  { id: "s7q-f2-002", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opening Accounts", difficulty: 2,
    stem: "A numbered account is permitted provided:",
    choices: ["The owner remains anonymous to the firm", "The firm holds written attestation of the true owner", "Only institutions use it", "It is approved by FINRA"],
    answerIndex: 1,
    explanation: "The number provides privacy on statements, but the firm must know and document the beneficial owner. An account whose owner the firm did not know would defeat the customer identification program outright." },
  { id: "s7q-f2-003", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opening Accounts", difficulty: 2,
    stem: "On notice of a customer's death the firm must:",
    choices: ["Liquidate the positions", "Transfer assets to the spouse", "Cancel open orders and freeze the account", "Continue under existing authority"],
    answerIndex: 2,
    explanation: "All prior authority — discretion, powers of attorney — ends at death. The firm freezes and awaits a death certificate, letters testamentary or of administration, and applicable tax waivers before acting." },
  { id: "s7q-f2-004", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opening Accounts", difficulty: 2,
    stem: "Which document allows a third party to trade but not withdraw assets?",
    choices: ["A full power of attorney", "A margin agreement", "A corporate resolution", "A limited power of attorney"],
    answerIndex: 3,
    explanation: "A limited power permits trading only; a FULL power adds the ability to withdraw cash and securities. Both must be written, and both differ from a representative's own discretionary authority." },
  { id: "s7q-f2-005", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opening Accounts", difficulty: 1,
    stem: "Every new account must be approved by:",
    choices: ["A principal", "The SEC", "FINRA", "The customer's attorney"],
    answerIndex: 0,
    explanation: "A principal approves every new account, and an options account additionally requires a registered options principal. Regulators do not approve individual accounts." },
  { id: "s7q-f2-006", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opening Accounts", difficulty: 2,
    stem: "A margin account requires the customer to sign:",
    choices: ["Nothing beyond the new account form", "A margin agreement", "A corporate resolution", "An options agreement"],
    answerIndex: 1,
    explanation: "The margin agreement contains the credit and hypothecation terms; loan consent is a separate and optional element. A CASH account requires no customer signature at all." },
  { id: "s7q-f2-007", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opening Accounts", difficulty: 2,
    stem: "In a JTWROS account, a deceased owner's interest passes to:",
    choices: ["The deceased's estate", "The firm", "The surviving owner", "A court appointee"],
    answerIndex: 2,
    explanation: "Right of survivorship transfers the interest automatically, outside probate. TENANTS IN COMMON is the registration that routes the share to the estate under the will." },
  { id: "s7q-f2-008", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opening Accounts", difficulty: 2,
    stem: "A UTMA account permits:",
    choices: ["Margin trading", "Multiple minors per account", "Revocation by the donor", "Prudent management for one minor by one custodian"],
    answerIndex: 3,
    explanation: "One custodian, one minor, and an irrevocable gift that legally belongs to the minor from transfer. Margin and speculation are barred because the standard is prudent management of someone else's property." },
  { id: "s7q-f2-009", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opening Accounts", difficulty: 3,
    stem: "A customer aged 68 with modest assets requests approval for uncovered call writing. The firm should:",
    choices: ["Decline, as the strategy carries unlimited loss and is unsuitable", "Approve with a signed waiver", "Approve if a principal signs", "Approve in a cash account only"],
    answerIndex: 0,
    explanation: "Naked call writing carries theoretically unlimited loss and demands substantial capital and sophistication. A waiver does not cure unsuitability, and the strategy cannot be done in a cash account at all — it requires margin." },
  { id: "s7q-f2-010", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opening Accounts", difficulty: 2,
    stem: "The options disclosure document must be delivered:",
    choices: ["Within 15 days of the first trade", "At or before account approval", "On request", "Annually"],
    answerIndex: 1,
    explanation: "The ODD reaches the customer at or before approval. Separately, the signed options agreement is due within 15 days of approval; without it the account may only CLOSE positions, not open new ones." },
  { id: "s7q-f4-001", examSlug: "series-7", topicId: "f4-process", topicName: "Processing Transactions", difficulty: 1,
    stem: "Regular-way settlement for a corporate stock trade is:",
    choices: ["T+2", "T+3", "T+1", "Same day"],
    answerIndex: 2,
    explanation: "T+1 since 28 May 2024 for stocks, corporate and municipal bonds, government securities and listed options. T+2 was the prior standard and still appears in outdated study material." },
  { id: "s7q-f4-002", examSlug: "series-7", topicId: "f4-process", topicName: "Processing Transactions", difficulty: 2,
    stem: "Which organisation nets firms' daily obligations?",
    choices: ["The DTC", "ACATS", "The transfer agent", "The NSCC"],
    answerIndex: 3,
    explanation: "The NSCC nets so firms settle differences rather than every gross transaction. DTC holds securities in book-entry form; ACATS moves whole customer accounts; the transfer agent keeps the issuer's ownership record." },
  { id: "s7q-f4-003", examSlug: "series-7", topicId: "f4-process", topicName: "Processing Transactions", difficulty: 2,
    stem: "A customer moving their entire account to another firm uses:",
    choices: ["ACATS", "DTC", "The NSCC", "The registrar"],
    answerIndex: 0,
    explanation: "The Automated Customer Account Transfer Service runs account transfers on a standard timetable. The other three serve clearing, custody and record-keeping functions respectively." },
  { id: "s7q-f4-004", examSlug: "series-7", topicId: "f4-process", topicName: "Processing Transactions", difficulty: 2,
    stem: "Which makes a delivery NOT in good form?",
    choices: ["Round-lot denominations", "A signature that does not match the registration", "A properly endorsed certificate", "Accompanying transfer documents"],
    answerIndex: 1,
    explanation: "Good delivery requires transferable form: correct denominations, proper endorsement, and a signature matching the registration. A mismatch, a mutilated certificate or missing documents cause the delivery to fail." },
  { id: "s7q-f4-005", examSlug: "series-7", topicId: "f4-process", topicName: "Processing Transactions", difficulty: 2,
    stem: "A confirmation must disclose the firm's:",
    choices: ["Net capital", "Profit on the trade", "Capacity as agent or principal", "Order routing revenue"],
    answerIndex: 2,
    explanation: "Capacity determines whether the customer paid a commission or a markup — different economics and different conflicts. Payment for order flow must be disclosed too, but through separate disclosures rather than on each confirmation." },
  { id: "s7q-f4-006", examSlug: "series-7", topicId: "f4-process", topicName: "Processing Transactions", difficulty: 2,
    stem: "Under Regulation T, customer payment is due:",
    choices: ["On the trade date", "On settlement date", "Within 30 days", "Two business days after settlement"],
    answerIndex: 3,
    explanation: "Settlement (T+1) is when firms exchange securities and money; Reg T is when the CUSTOMER pays their firm, two business days later. Missing it triggers a sell-out and a 90-day freeze." },
  { id: "s7q-f4-007", examSlug: "series-7", topicId: "f4-process", topicName: "Processing Transactions", difficulty: 2,
    stem: "A 'when issued' trade settles:",
    choices: ["Once the security is actually issued", "T+1", "Same day", "Never"],
    answerIndex: 0,
    explanation: "When-issued trading occurs before a security exists — common for new municipal issues and Treasury auctions — and settles once issuance completes. Confirmations show no settlement date until then." },
  { id: "s7q-f4-008", examSlug: "series-7", topicId: "f4-process", topicName: "Processing Transactions", difficulty: 1,
    stem: "Customer securities held by a firm must be:",
    choices: ["Held in the firm's trading account", "Segregated from firm assets", "Pledged for firm loans", "Lent automatically"],
    answerIndex: 1,
    explanation: "Segregation keeps customer property identifiable and protected if the firm fails. Mixing it with firm assets is COMMINGLING; lending it out requires the customer's separate loan consent." },
  { id: "s7q-f4-009", examSlug: "series-7", topicId: "f4-process", topicName: "Processing Transactions", difficulty: 2,
    stem: "Account statements must be sent at minimum:",
    choices: ["Annually", "Monthly always", "Quarterly, and monthly with activity", "On request"],
    answerIndex: 2,
    explanation: "Quarterly is the floor, monthly in any month with activity. Confirmations are the separate per-trade document due at or before completion." },
  { id: "s7q-f4-010", examSlug: "series-7", topicId: "f4-process", topicName: "Processing Transactions", difficulty: 3,
    stem: "A customer asks that all confirmations go to their accountant instead of to them. The firm should:",
    choices: ["Comply and stop sending to the customer", "Refuse entirely", "Send only to the accountant", "Send duplicates to the accountant and originals to the customer"],
    answerIndex: 3,
    explanation: "The owner must continue receiving their own confirmations and statements. Duplicates to a third party are permitted on written instruction, but diverting the originals away from the customer is a recognised concealment red flag." },
];
