// ============================================================
// Certus — Series 66 Full Mock Exam bank
// ORIGINAL questions written to the NASAA Series 66 content outline.
// Reserved for the mock; these never appear in practice drills, so a
// sitting is always "unseen."
//
// Authenticity (verified against the NASAA Series 66 outline):
//   · 100 scored questions, one 150-minute session, 90 s/question
//   · Passing score 73 of 100 scored questions
//   · The real exam adds 10 unscored pretest items; we present 100
//     scored questions so the reported score is directly comparable
//   · Blueprint weights (NASAA, eff. June 12 2023):
//       Economic Factors ..............  8 questions  (8%)
//       Investment Vehicles ........... 17 questions (17%)
//       Client Recommendations ........ 30 questions (30%)
//       Laws and Regulations .......... 45 questions (45%)
//
// S66_MOCK_FULL  — the 100-question sit-down exam
// S66_MOCK_QUICK — a 15-question blueprint-weighted readiness sample
// ============================================================

import { Question } from "./types";

// ============================================================
// ECONOMIC FACTORS AND BUSINESS INFORMATION (8, 8%)
// ============================================================
const EC: Question[] = [
  { id: "s66m-ec-000", examSlug: "series-66", topicId: "economics", topicName: "Economic Factors and Business Information", difficulty: 1,
    stem: "An inverted yield curve is most often interpreted as signalling:",
    choices: ["An approaching slowdown", "Accelerating growth", "Rising inflation only", "A stable economy"],
    answerIndex: 0,
    explanation: "It reflects an expectation that policy rates will be cut, which follows from expected weakness." },
  { id: "s66m-ec-001", examSlug: "series-66", topicId: "economics", topicName: "Economic Factors and Business Information", difficulty: 3,
    stem: "The Federal Reserve's most frequently used policy tool is:",
    choices: ["The discount rate", "Open market operations", "Reserve requirements", "Margin requirements"],
    answerIndex: 1,
    explanation: "Buying securities injects reserves and lowers rates; selling does the opposite." },
  { id: "s66m-ec-002", examSlug: "series-66", topicId: "economics", topicName: "Economic Factors and Business Information", difficulty: 2,
    stem: "An increase in the money supply, all else equal, tends to:",
    choices: ["Raise rates for the client", "Have no effect in most cases", "Lower short-term interest rates", "Raise unemployment as stated"],
    answerIndex: 2,
    explanation: "The effect on inflation operates with a lag and depends on the state of the economy." },
  { id: "s66m-ec-003", examSlug: "series-66", topicId: "economics", topicName: "Economic Factors and Business Information", difficulty: 1,
    stem: "Fiscal policy is conducted through:",
    choices: ["Interest rates", "Reserve requirements", "Open market operations", "Government spending and taxation"],
    answerIndex: 3,
    explanation: "Monetary policy is the central bank's domain; fiscal policy belongs to the legislature and treasury." },
  { id: "s66m-ec-004", examSlug: "series-66", topicId: "economics", topicName: "Economic Factors and Business Information", difficulty: 3,
    stem: "A leading economic indicator is one that:",
    choices: ["Turns before the broader economy", "Turns after it for the client", "Moves with it for the client", "Does not move for the client"],
    answerIndex: 0,
    explanation: "Building permits and new orders lead; unemployment lags; industrial production is coincident." },
  { id: "s66m-ec-005", examSlug: "series-66", topicId: "economics", topicName: "Economic Factors and Business Information", difficulty: 2,
    stem: "Purchasing power risk is the risk that:",
    choices: ["Rates rise", "Inflation erodes real returns", "An issuer defaults", "Liquidity disappears"],
    answerIndex: 1,
    explanation: "It is most damaging to long-dated fixed nominal cash flows." },
  { id: "s66m-ec-006", examSlug: "series-66", topicId: "economics", topicName: "Economic Factors and Business Information", difficulty: 1,
    stem: "A strengthening domestic currency tends to:",
    choices: ["Raise export volumes sharply", "Have no effect on trade at all", "Cheapen imports, hurt exports", "Push domestic inflation higher"],
    answerIndex: 2,
    explanation: "A weakening currency reverses both effects." },
  { id: "s66m-ec-007", examSlug: "series-66", topicId: "economics", topicName: "Economic Factors and Business Information", difficulty: 2,
    stem: "Correlation of +1.0 between two assets means:",
    choices: ["They move oppositely", "They are unrelated", "One is riskless", "They move together identically"],
    answerIndex: 3,
    explanation: "Diversification benefit requires correlation below one, and it improves as correlation falls." },
];

// ============================================================
// INVESTMENT VEHICLE CHARACTERISTICS (17, 17%)
// ============================================================
const VE: Question[] = [
  { id: "s66m-ve-000", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 1,
    stem: "A bond selling at a discount has a yield to maturity that is:",
    choices: ["Above its coupon rate", "Below its coupon", "Equal to the coupon", "Zero"],
    answerIndex: 0,
    explanation: "A premium bond reverses the relationship, with yield to maturity below the coupon." },
  { id: "s66m-ve-001", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 2,
    stem: "Duration measures a bond's sensitivity to:",
    choices: ["Credit changes", "Interest rate changes", "Inflation only", "Currency"],
    answerIndex: 1,
    explanation: "Longer maturity and lower coupon both increase duration." },
  { id: "s66m-ve-002", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 2,
    stem: "A zero-coupon bond's duration equals:",
    choices: ["Half its maturity", "Zero", "Its maturity", "Its coupon"],
    answerIndex: 2,
    explanation: "The absence of interim cash flows removes all reinvestment risk for a held-to-maturity investor." },
  { id: "s66m-ve-003", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 1,
    stem: "The principal risk of a long-dated fixed-rate bond is:",
    choices: ["Reinvestment risk only", "Credit risk only", "Liquidity", "Interest rate risk"],
    answerIndex: 3,
    explanation: "Purchasing power risk is the related concern for a long nominal claim." },
  { id: "s66m-ve-004", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 3,
    stem: "A callable bond's call feature benefits:",
    choices: ["The issuer", "The bondholder", "Both equally", "Neither"],
    answerIndex: 0,
    explanation: "The issuer calls when rates fall, which caps the bondholder's price appreciation." },
  { id: "s66m-ve-005", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 3,
    stem: "Common stock's claim on assets in liquidation is:",
    choices: ["First", "Last, after all other claims", "Equal to bonds", "Ahead of preferred"],
    answerIndex: 1,
    explanation: "That residual position is paired with unlimited upside participation." },
  { id: "s66m-ve-006", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 1,
    stem: "Preferred stock differs from common in offering:",
    choices: ["Voting control for the client", "Higher growth for the client", "A fixed dividend with payment priority", "Tax deduction for the client"],
    answerIndex: 2,
    explanation: "Cumulative preferred requires arrears to be paid before any common dividend." },
  { id: "s66m-ve-007", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 2,
    stem: "An open-end fund's shares are purchased at:",
    choices: ["The market price for the client", "A discount for the client", "Par for the client", "Net asset value plus any sales charge"],
    answerIndex: 3,
    explanation: "Forward pricing means the order fills at the next computed NAV rather than the last." },
  { id: "s66m-ve-008", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 3,
    stem: "A closed-end fund's market price:",
    choices: ["Can differ from net asset value", "Always equals NAV", "Is fixed", "Is set by the adviser"],
    answerIndex: 0,
    explanation: "The fixed share count means demand must be absorbed by price rather than by issuing shares." },
  { id: "s66m-ve-009", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 1,
    stem: "An exchange-traded fund maintains its price near NAV through:",
    choices: ["Manager intervention as stated", "Creation and redemption arbitrage", "Regulation for the client", "Fixed pricing for the client"],
    answerIndex: 1,
    explanation: "Authorised participants exchange securities baskets for fund shares to close any gap." },
  { id: "s66m-ve-010", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 2,
    stem: "A unit investment trust differs from a mutual fund in having:",
    choices: ["Active management for the client", "No portfolio for the client", "A fixed portfolio and no active management", "Daily trading for the client"],
    answerIndex: 2,
    explanation: "It also has a stated termination date rather than existing indefinitely." },
  { id: "s66m-ve-011", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 2,
    stem: "A variable annuity's value during accumulation depends on:",
    choices: ["A guaranteed rate", "The insurer's general account", "Prevailing rates", "Subaccount investment performance"],
    answerIndex: 3,
    explanation: "A fixed annuity instead pays from the general account at a rate the insurer guarantees." },
  { id: "s66m-ve-012", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 1,
    stem: "The mortality and expense charge in a variable annuity compensates the insurer for:",
    choices: ["Mortality risk and expense guarantees", "Investment losses for the client", "Taxes for the client", "Commissions only for the client"],
    answerIndex: 0,
    explanation: "It is one of several layered charges that make the total cost higher than a mutual fund's." },
  { id: "s66m-ve-013", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 2,
    stem: "An immediate annuity begins payments:",
    choices: ["After ten years for the client", "Within one payment period of purchase", "At age 70 for the client", "Never for the client"],
    answerIndex: 1,
    explanation: "A deferred annuity accumulates first and annuitises later." },
  { id: "s66m-ve-014", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 2,
    stem: "A life-only annuity payout option provides:",
    choices: ["The smallest payment for the client", "A guaranteed period for the client", "The largest payment with no survivor benefit", "A lump sum for the client"],
    answerIndex: 2,
    explanation: "Adding a period certain or joint life reduces the payment in exchange for the guarantee." },
  { id: "s66m-ve-015", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 1,
    stem: "An option contract's holder has:",
    choices: ["An obligation", "A guaranteed profit", "A dividend claim", "A right, not an obligation"],
    answerIndex: 3,
    explanation: "The writer holds the corresponding obligation, which is why the writer receives a premium." },
  { id: "s66m-ve-016", examSlug: "series-66", topicId: "vehicles", topicName: "Investment Vehicle Characteristics", difficulty: 3,
    stem: "A REIT must distribute at least 90% of taxable income to:",
    choices: ["Avoid entity-level taxation", "Satisfy the SEC", "Maintain a listing", "Pay its adviser"],
    answerIndex: 0,
    explanation: "It does not pass through losses, which distinguishes it from a limited partnership." },
];

// ============================================================
// CLIENT RECOMMENDATIONS AND STRATEGIES (30, 30%)
// ============================================================
const RC: Question[] = [
  { id: "s66m-re-000", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 1,
    stem: "An investment policy statement should record objectives and:",
    choices: ["Only the return target for the client", "Constraints including horizon and liquidity", "Only the benchmark for the client", "Only fees for the client"],
    answerIndex: 1,
    explanation: "Tax status, legal circumstances and unique preferences complete the constraint set." },
  { id: "s66m-re-001", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 3,
    stem: "A client's risk capacity differs from risk tolerance in being:",
    choices: ["Emotional for the client", "Self-reported for the client", "Objective and circumstance-driven", "Unmeasurable for the client"],
    answerIndex: 2,
    explanation: "Where the two conflict, the plan must respect the lower of them." },
  { id: "s66m-re-002", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 2,
    stem: "An investor with a long horizon and stable income generally has:",
    choices: ["Lower ability as stated", "No ability in most cases", "Fixed ability as stated", "Higher ability to take risk"],
    answerIndex: 3,
    explanation: "Willingness is assessed separately, and the recommendation must respect both." },
  { id: "s66m-re-003", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 1,
    stem: "Diversification reduces:",
    choices: ["Unsystematic risk", "Systematic risk", "All risk", "Market risk"],
    answerIndex: 0,
    explanation: "Market risk remains regardless of how many securities are held." },
  { id: "s66m-re-004", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 3,
    stem: "A portfolio's capital market line plots expected return against:",
    choices: ["Beta of the portfolio in practice", "Standard deviation of the portfolio", "Duration of the portfolio's bonds", "Turnover of the portfolio's holdings"],
    answerIndex: 1,
    explanation: "The capital market line uses total risk on its horizontal axis; the security market line is the one plotted against beta." },
  { id: "s66m-re-005", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 2,
    stem: "The Sharpe ratio divides excess return by:",
    choices: ["Beta", "Tracking error", "Total volatility", "Duration"],
    answerIndex: 2,
    explanation: "It is the appropriate measure where the portfolio represents the investor's entire wealth." },
  { id: "s66m-re-006", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 1,
    stem: "An efficient portfolio offers:",
    choices: ["The lowest return for the client", "Zero risk for the client", "Guaranteed return for the client", "The highest return for its risk level"],
    answerIndex: 3,
    explanation: "Portfolios below the efficient frontier are dominated by others offering more return for the same risk." },
  { id: "s66m-re-007", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 2,
    stem: "Dollar cost averaging involves investing:",
    choices: ["A fixed amount at regular intervals", "A fixed number of shares", "Everything at once", "Only after declines"],
    answerIndex: 0,
    explanation: "It results in more shares bought at lower prices, and its main benefit is behavioural." },
  { id: "s66m-re-008", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 3,
    stem: "Strategic asset allocation refers to:",
    choices: ["Short-term tilts", "The long-term policy mix", "Security selection", "Trade timing"],
    answerIndex: 1,
    explanation: "Tactical allocation is the deliberate short-term deviation from that policy mix." },
  { id: "s66m-re-009", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 1,
    stem: "Rebalancing a portfolio back to target weights requires:",
    choices: ["Selling losers for the client", "No transactions for the client", "Selling winners and buying losers", "Adding leverage for the client"],
    answerIndex: 2,
    explanation: "It runs against the disposition effect, which is why a written policy helps." },
  { id: "s66m-re-010", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 2,
    stem: "A client's essential spending needs should be funded from:",
    choices: ["The highest-return assets", "Illiquid holdings", "Leveraged positions", "Lower-risk assets"],
    answerIndex: 3,
    explanation: "Goals-based structuring matches the asset's risk to the goal's importance and horizon." },
  { id: "s66m-re-011", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 2,
    stem: "Capital gains on securities held longer than one year are generally taxed at:",
    choices: ["Long-term rates", "Ordinary income rates", "Zero", "Corporate rates"],
    answerIndex: 0,
    explanation: "The holding period runs from the day after acquisition through the disposal date." },
  { id: "s66m-re-012", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 1,
    stem: "A wash sale occurs when a security is sold at a loss and repurchased within:",
    choices: ["One year", "30 days before or after", "90 days", "The same day only"],
    answerIndex: 1,
    explanation: "The disallowed loss is added to the basis of the replacement shares rather than lost entirely." },
  { id: "s66m-re-013", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 3,
    stem: "The cost basis of inherited securities is generally:",
    choices: ["The decedent's basis as stated", "Zero for the client", "Stepped up to date-of-death value", "The purchase price in practice"],
    answerIndex: 2,
    explanation: "Gifted securities instead generally carry over the donor's basis." },
  { id: "s66m-re-014", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 2,
    stem: "Qualified dividends are taxed at:",
    choices: ["Ordinary income rates", "Zero always", "Corporate rates", "Long-term capital gains rates"],
    answerIndex: 3,
    explanation: "A holding period requirement must be met for the dividend to qualify." },
  { id: "s66m-re-015", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 1,
    stem: "Municipal bond interest is generally exempt from:",
    choices: ["Federal income tax", "All taxes", "Estate tax", "Capital gains tax"],
    answerIndex: 0,
    explanation: "Capital gains on a municipal bond sold above basis remain fully taxable." },
  { id: "s66m-re-016", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 3,
    stem: "A traditional IRA contribution may be deductible depending on:",
    choices: ["Age only for the client", "Income and workplace plan coverage", "Marital status only in practice", "The custodian for the client"],
    answerIndex: 1,
    explanation: "A Roth IRA contribution is never deductible but qualified withdrawals are tax free." },
  { id: "s66m-re-017", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 2,
    stem: "Roth IRA qualified distributions require the account to be held at least:",
    choices: ["One year from the first deposit", "Ten years from establishment", "Five years, plus an age test", "No holding period at all"],
    answerIndex: 2,
    explanation: "Contributions may be withdrawn at any time without tax or penalty, unlike earnings." },
  { id: "s66m-re-018", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 1,
    stem: "A 401(k) plan's contributions are made:",
    choices: ["By the employer only", "After tax only", "By the custodian", "Through salary deferral"],
    answerIndex: 3,
    explanation: "Employer matching contributions are additional and may be subject to a vesting schedule." },
  { id: "s66m-re-019", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 2,
    stem: "A defined benefit plan places investment risk on:",
    choices: ["The employer", "The employee", "The custodian", "The trustee"],
    answerIndex: 0,
    explanation: "A defined contribution plan shifts that risk to the participant." },
  { id: "s66m-re-020", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 3,
    stem: "Required minimum distributions from a traditional IRA are:",
    choices: ["Tax free", "Taxable as ordinary income", "Taxed at capital gains rates", "Exempt"],
    answerIndex: 1,
    explanation: "Failure to take the required amount attracts a substantial excise penalty." },
  { id: "s66m-re-021", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 1,
    stem: "A rollover from a qualified plan must generally be completed within:",
    choices: ["30 days", "One year", "60 days", "Immediately"],
    answerIndex: 2,
    explanation: "A direct trustee-to-trustee transfer avoids the deadline and any withholding." },
  { id: "s66m-re-022", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 2,
    stem: "A 529 plan's earnings are federally tax free when used for:",
    choices: ["Any purpose in most cases", "Retirement for the client", "Medical costs in practice", "Qualified education expenses"],
    answerIndex: 3,
    explanation: "Non-qualified withdrawals attract tax on earnings plus a penalty." },
  { id: "s66m-re-023", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 2,
    stem: "Assets placed in an irrevocable trust are generally:",
    choices: ["Removed from the grantor's taxable estate", "Still controlled fully by the grantor", "Reportable on the grantor's own return", "Returnable to the grantor on demand"],
    answerIndex: 0,
    explanation: "Surrendering control and the power to revoke is what removes the assets from the estate; a revocable trust avoids probate but keeps them in it." },
  { id: "s66m-re-024", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 1,
    stem: "An irrevocable trust generally removes assets from the estate at the cost of:",
    choices: ["Higher fees", "Surrendering control", "Probate exposure", "Immediate tax"],
    answerIndex: 1,
    explanation: "Irreversibility is the trade-off that produces the estate tax benefit." },
  { id: "s66m-re-025", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 3,
    stem: "A durable power of attorney remains effective:",
    choices: ["Only while competent for the client", "For one year for the client", "After the principal becomes incapacitated", "Until revoked by the agent in practice"],
    answerIndex: 2,
    explanation: "A springing power instead becomes effective only upon incapacity." },
  { id: "s66m-re-026", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 2,
    stem: "An adviser recommending a variable annuity inside an IRA should recognise:",
    choices: ["It doubles the deferral for the client", "It reduces fees for the client", "It is required for the client", "The tax deferral is already provided by the IRA"],
    answerIndex: 3,
    explanation: "The annuity's additional cost buys a benefit the account already provides." },
  { id: "s66m-re-027", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 1,
    stem: "An adviser recommending a switch between mutual fund families should consider:",
    choices: ["Sales charges and any breakpoint lost", "Only performance for the client", "Only the fee for the client", "Nothing for the client"],
    answerIndex: 0,
    explanation: "Frequent switching to generate commissions is a recognised sales practice violation." },
  { id: "s66m-re-028", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 3,
    stem: "A recommendation must be suitable based on the client's:",
    choices: ["Recent returns for the client", "Objectives, circumstances and risk tolerance", "Peer holdings for the client", "Adviser preference for the client"],
    answerIndex: 1,
    explanation: "Suitability is assessed across the whole portfolio rather than security by security." },
  { id: "s66m-re-029", examSlug: "series-66", topicId: "recommendations", topicName: "Client Recommendations and Strategies", difficulty: 2,
    stem: "An adviser managing a concentrated position should weigh:",
    choices: ["Only the tax for the client", "Only diversification for the client", "Diversification benefit against tax cost", "Neither for the client"],
    answerIndex: 2,
    explanation: "Staged sales, exchange funds and hedging are the standard tools for the trade-off." },
];

// ============================================================
// LAWS, REGULATIONS, AND GUIDELINES (45, 45%)
// ============================================================
const LA: Question[] = [
  { id: "s66m-la-000", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "The Uniform Securities Act is:",
    choices: ["A federal statute for the client", "An SEC rule for the client", "A FINRA rule for the client", "Model legislation adopted state by state"],
    answerIndex: 3,
    explanation: "Its provisions vary in adoption, which is why state law differs across jurisdictions." },
  { id: "s66m-la-001", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "An investment adviser is defined as one who, for compensation, engages in:",
    choices: ["Advising on securities for pay", "Giving any financial advice", "Selling securities to the public", "Holding custody of assets"],
    answerIndex: 0,
    explanation: "All three prongs of the definition must be satisfied for registration to be required." },
  { id: "s66m-la-002", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "An adviser with assets under management of $150 million registers with:",
    choices: ["The state only", "The SEC", "Neither", "FINRA"],
    answerIndex: 1,
    explanation: "Advisers below $100 million generally register with the states, with a buffer zone between." },
  { id: "s66m-la-003", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "An investment adviser representative registers with:",
    choices: ["The SEC", "FINRA", "The state", "Nobody"],
    answerIndex: 2,
    explanation: "The firm's registration and the individual's registration are separate requirements." },
  { id: "s66m-la-004", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 3,
    stem: "A broker-dealer is distinguished from an investment adviser by:",
    choices: ["Charging fees for its services", "Holding custody of client assets", "Being registered with a regulator", "Effecting transactions for others"],
    answerIndex: 3,
    explanation: "The broker-dealer exclusion applies where advice is solely incidental and no special compensation is received." },
  { id: "s66m-la-005", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "An adviser who takes custody of client funds must:",
    choices: ["Meet safeguards including examination", "Do nothing beyond normal practice", "Post a surety bond and nothing more", "Notify affected clients and nothing more"],
    answerIndex: 0,
    explanation: "Qualified custodian requirements and account statement delivery are among the safeguards." },
  { id: "s66m-la-006", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "An adviser's annual updating amendment to Form ADV is due within:",
    choices: ["30 days of the fiscal year end", "90 days of the fiscal year end", "180 days of the fiscal year end", "One year of the fiscal year end"],
    answerIndex: 1,
    explanation: "The annual updating amendment is due within 90 days of fiscal year end; material changes to certain items require a prompt amendment sooner." },
  { id: "s66m-la-007", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 3,
    stem: "Form ADV Part 2 is written in:",
    choices: ["Tabular form", "Code", "Plain English narrative", "Legal citation form"],
    answerIndex: 2,
    explanation: "Part 2A describes the firm and Part 2B the supervised persons providing advice." },
  { id: "s66m-la-008", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 3,
    stem: "An adviser's fiduciary duty requires:",
    choices: ["Best execution only", "Disclosure only", "Suitability only", "Placing client interests first"],
    answerIndex: 3,
    explanation: "It comprises duties of loyalty and care, and it is broader than a suitability standard." },
  { id: "s66m-la-009", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "A conflict of interest must be:",
    choices: ["Fully and fairly disclosed", "Eliminated always", "Ignored", "Disclosed only if asked"],
    answerIndex: 0,
    explanation: "Disclosure must be specific enough for the client to understand and consent to the conflict." },
  { id: "s66m-la-010", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "An adviser charging performance-based fees may generally do so only for:",
    choices: ["Any client for the client", "Qualified clients meeting thresholds", "Institutions only for the client", "Nobody for the client"],
    answerIndex: 1,
    explanation: "The restriction exists because performance fees can bias the adviser toward excess risk." },
  { id: "s66m-la-011", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "An adviser's advertisement may include testimonials only with:",
    choices: ["No conditions of any kind", "Prior approval from the SEC", "Disclosures on pay and conflicts", "Consent from the client alone"],
    answerIndex: 2,
    explanation: "The modernised marketing rule permits them subject to those disclosure conditions." },
  { id: "s66m-la-012", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "Agency cross transactions by an adviser require:",
    choices: ["No consent from the client", "Verbal consent from the client", "Approval from the regulator", "Advance written consent"],
    answerIndex: 3,
    explanation: "The consent must be revocable and accompanied by specific disclosures." },
  { id: "s66m-la-013", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "An adviser's use of soft dollars is limited to:",
    choices: ["Research and brokerage services", "Any expense the firm incurs", "Marketing and promotional costs", "Office rent and overheads"],
    answerIndex: 0,
    explanation: "The safe harbour is narrower than many firms assume, and overhead is outside it." },
  { id: "s66m-la-014", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "Registration of a security by coordination is used when:",
    choices: ["No federal filing has been made", "A federal filing accompanies it", "The issuer itself is exempt", "Only the state requires filing"],
    answerIndex: 1,
    explanation: "Registration by qualification is the route where no federal registration accompanies the offering." },
  { id: "s66m-la-015", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "An exempt security under the Uniform Securities Act includes:",
    choices: ["All corporate stock in practice", "Any bond for the client", "Government and municipal securities", "Options for the client"],
    answerIndex: 2,
    explanation: "An exempt transaction is a separate category based on how the sale occurs rather than what is sold." },
  { id: "s66m-la-016", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 3,
    stem: "A private placement to a limited number of buyers is:",
    choices: ["An exempt security", "Prohibited", "Always registered", "An exempt transaction"],
    answerIndex: 3,
    explanation: "The exemption attaches to the transaction, so the same security sold publicly would require registration." },
  { id: "s66m-la-017", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "An isolated non-issuer transaction is:",
    choices: ["An exempt transaction", "An exempt security", "Prohibited", "Always registered"],
    answerIndex: 0,
    explanation: "The distinction between exempt securities and exempt transactions is regularly tested." },
  { id: "s66m-la-018", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "The Administrator may deny, suspend or revoke a registration when it is:",
    choices: ["At the Administrator's discretion", "In the public interest, for cause", "At a competitor's request", "Automatically on any complaint"],
    answerIndex: 1,
    explanation: "The person is entitled to notice, an opportunity for hearing and written findings." },
  { id: "s66m-la-019", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 3,
    stem: "A private civil action under the Uniform Securities Act must be brought within:",
    choices: ["Five years of discovery in all cases", "One year of the sale in every case", "Two years of discovery, three of sale", "Six months of discovering the fraud"],
    answerIndex: 2,
    explanation: "The Act sets the sooner of two years after discovery of the violation or three years after the sale or contract of sale." },
  { id: "s66m-la-020", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 3,
    stem: "The statute of limitations for civil action under the Uniform Securities Act is generally:",
    choices: ["One year from the transaction", "Ten years from the violation", "No limitation period at all", "Two years after discovery"],
    answerIndex: 3,
    explanation: "The earlier of the two periods applies, which is the detail most often tested." },
  { id: "s66m-la-021", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "A client's civil remedy for a securities law violation typically includes:",
    choices: ["Rescission with interest", "Punitive damages and nothing else", "No remedy of any kind", "Treble damages in every case"],
    answerIndex: 0,
    explanation: "The remedy is designed to restore the client rather than to punish the seller." },
  { id: "s66m-la-022", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "Fraud under the Uniform Securities Act applies to:",
    choices: ["Registered securities only", "Any security, exempt or not", "Exempt securities only", "Municipal bonds only"],
    answerIndex: 1,
    explanation: "The antifraud provisions are the one area with no exemption of any kind." },
  { id: "s66m-la-023", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "An adviser guaranteeing a client against loss is:",
    choices: ["Permitted with disclosure", "Required", "Prohibited", "Permitted for institutions"],
    answerIndex: 2,
    explanation: "Sharing in profits and losses is separately restricted and requires specific conditions." },
  { id: "s66m-la-024", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "An adviser borrowing money from a client is generally:",
    choices: ["Permitted in every circumstance", "Permitted where it is disclosed", "Merely required to be reported", "Prohibited, with narrow exceptions"],
    answerIndex: 3,
    explanation: "Lending to a client is subject to a parallel restriction." },
  { id: "s66m-la-025", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "Commingling client funds with the adviser's own is:",
    choices: ["Prohibited", "Permitted with consent", "Standard practice", "Required"],
    answerIndex: 0,
    explanation: "It is among the most serious violations because it puts client assets directly at risk." },
  { id: "s66m-la-026", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "An adviser must maintain books and records for at least:",
    choices: ["One year from the year end", "Five years from the year end", "Three years from the year end", "Ten years from the year end"],
    answerIndex: 1,
    explanation: "The requirement runs from the end of the fiscal year in which the record was made." },
  { id: "s66m-la-027", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "The National Securities Markets Improvement Act preempted state registration of:",
    choices: ["All securities", "Municipal bonds", "Federal covered securities", "Nothing"],
    answerIndex: 2,
    explanation: "States retain antifraud authority and may require notice filings and fees." },
  { id: "s66m-la-028", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 3,
    stem: "A state may require a notice filing for a federal covered adviser but may not:",
    choices: ["Charge a filing fee for it", "Investigate suspected fraud", "Receive a copy of Form ADV", "Impose substantive registration"],
    answerIndex: 3,
    explanation: "The division of authority between federal and state regulators is a recurring exam theme." },
  { id: "s66m-la-029", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "An agent of a broker-dealer must register in a state where:",
    choices: ["They have clients or solicit there", "They reside only", "The firm is located only", "Never"],
    answerIndex: 0,
    explanation: "The de minimis exemption may apply to an existing client who is temporarily in the state." },
  { id: "s66m-la-030", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "An adviser's assignment of an advisory contract requires:",
    choices: ["Notice only", "Client consent", "Nothing", "Regulatory approval"],
    answerIndex: 1,
    explanation: "A change in control of a partnership adviser requires notice rather than consent." },
  { id: "s66m-la-031", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 3,
    stem: "An investment adviser contract must state:",
    choices: ["The return the client can expect", "The benchmark used for reporting", "Services, fees and assignment terms", "The identity of the custodian"],
    answerIndex: 2,
    explanation: "It must also state that the adviser will not be compensated on capital gains except as permitted." },
  { id: "s66m-la-032", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 3,
    stem: "Insider trading under federal law prohibits trading on:",
    choices: ["Any information in practice", "Public information as stated", "Analyst opinions in practice", "Material non-public information"],
    answerIndex: 3,
    explanation: "Liability extends to tipping others who then trade on the information." },
  { id: "s66m-la-033", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "The Investment Company Act of 1940 regulates:",
    choices: ["Mutual funds and similar vehicles", "Registered broker-dealer firms", "Investment advisers and no others", "National securities exchanges"],
    answerIndex: 0,
    explanation: "It classifies companies as face-amount certificate companies, unit investment trusts or management companies." },
  { id: "s66m-la-034", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "The Securities Exchange Act of 1934 created:",
    choices: ["Only the primary market in practice", "The SEC and regulates secondary trading", "State regulators for the client", "FINRA for the client"],
    answerIndex: 1,
    explanation: "The Securities Act of 1933 governs the primary market and new issue registration." },
  { id: "s66m-la-035", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "Regulation Best Interest applies to:",
    choices: ["Investment advisers and no others", "Institutional accounts and no others", "Broker-dealer retail recommendations", "No category of firm at all"],
    answerIndex: 2,
    explanation: "It imposes care, disclosure, conflict and compliance obligations on the recommendation." },
  { id: "s66m-la-036", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "Form CRS is a relationship summary provided to:",
    choices: ["Institutions", "Regulators only", "Employees", "Retail investors"],
    answerIndex: 3,
    explanation: "It must be delivered at or before the earliest of a recommendation or an account opening." },
  { id: "s66m-la-037", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "An adviser's fiduciary standard compared with Regulation Best Interest is:",
    choices: ["Broader and ongoing", "Narrower", "Identical", "Inapplicable"],
    answerIndex: 0,
    explanation: "The fiduciary duty applies throughout the relationship rather than at the point of recommendation." },
  { id: "s66m-la-038", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "An adviser discovering a material error in a client's account must:",
    choices: ["Correct it silently as stated", "Correct it and inform the client", "Await inquiry for the client", "Offset it later in most cases"],
    answerIndex: 1,
    explanation: "Concealment converts an operational error into a fiduciary breach." },
  { id: "s66m-la-039", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "Anti-money-laundering obligations require firms to:",
    choices: ["Do nothing beyond normal practice", "Report every trade to regulators", "Verify identity and monitor activity", "Refuse all cash transactions"],
    answerIndex: 2,
    explanation: "A customer must not be told that a suspicious activity report has been filed." },
  { id: "s66m-la-040", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 3,
    stem: "Business continuity planning is required so that a firm can:",
    choices: ["Reduce the fees it charges clients", "Increase the returns it achieves", "Avoid the need to register", "Keep serving clients after disruption"],
    answerIndex: 3,
    explanation: "Succession planning for a solo adviser is a recognised component of the obligation." },
  { id: "s66m-la-041", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "Cybersecurity obligations for an adviser include:",
    choices: ["Safeguarding client information", "No specific obligation at all", "Encryption and nothing further", "Staff training and nothing else"],
    answerIndex: 0,
    explanation: "Regulation S-P requires policies reasonably designed to protect customer records." },
  { id: "s66m-la-042", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 1,
    stem: "An adviser's supervision obligation extends to:",
    choices: ["Nothing for the client", "Supervised persons' advisory activities", "Only trading for the client", "Only marketing for the client"],
    answerIndex: 1,
    explanation: "The compliance programme must be reviewed at least annually for adequacy." },
  { id: "s66m-la-043", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 2,
    stem: "A chief compliance officer must be designated by:",
    choices: ["Broker-dealers only in practice", "Large firms only for the client", "Every registered investment adviser", "Nobody for the client"],
    answerIndex: 2,
    explanation: "The role carries responsibility for administering the firm's written compliance policies." },
  { id: "s66m-la-044", examSlug: "series-66", topicId: "laws", topicName: "Laws, Regulations, and Guidelines", difficulty: 3,
    stem: "An adviser's annual compliance review must be:",
    choices: ["Verbal", "Optional", "Performed by an auditor", "Documented"],
    answerIndex: 3,
    explanation: "It should assess whether the policies remain adequate and are being followed effectively." },
];

export const S66_MOCK_FULL: Question[] = [...EC, ...VE, ...RC, ...LA];

// Blueprint-weighted 15-question readiness sample: 1 EC, 3 VE, 4 RC, 7 LA
export const S66_MOCK_QUICK: Question[] = [
  EC[0],
  VE[0], VE[6], VE[12],
  RC[0], RC[8], RC[16], RC[24],
  LA[0], LA[6], LA[12], LA[18], LA[26], LA[34], LA[42],
];

export const S66_FULL_READY = true;
