// ============================================================
// Certus — Series 7 Full Mock Exam bank
// ORIGINAL questions written to the FINRA Series 7 content outline.
// Reserved for the mock; these never appear in practice drills, so a
// sitting is always "unseen."
//
// Authenticity (verified against the FINRA Series 7 study outline):
//   · 125 scored questions, one 3 h 45 m session, ~108 s/question
//   · Passing score 72%
//   · Four answer choices (A/B/C/D)
//   · Blueprint weights by major job function:
//       F1 Seeks Business ................  9 questions  (7%)
//       F2 Opens Accounts ................ 11 questions  (9%)
//       F3 Information & Recommendations . 91 questions (73%)
//       F4 Processes Transactions ........ 14 questions (11%)
//   · Current rules: T+1 settlement (since May 2024)
//
// S7_MOCK_FULL  — the 125-question sit-down exam
// S7_MOCK_QUICK — a 15-question blueprint-weighted readiness sample
// ============================================================

import { Question } from "./types";

// ============================================================
// F1 — SEEKS BUSINESS FOR THE BROKER-DEALER (9, 7%)
// ============================================================
const F1: Question[] = [
  { id: "s7m-f1-000", examSlug: "series-7", topicId: "f1-business", topicName: "Seeks Business for the Broker-Dealer", difficulty: 1,
    stem: "A registered representative's social media post recommending a specific stock is treated as:",
    choices: ["A retail communication needing approval", "Private correspondence with a client", "An internal firm-use-only document", "A communication exempt from review"],
    answerIndex: 0,
    explanation: "Retail communications distributed to more than 25 retail investors in 30 days require prior principal approval and recordkeeping." },
  { id: "s7m-f1-001", examSlug: "series-7", topicId: "f1-business", topicName: "Seeks Business for the Broker-Dealer", difficulty: 3,
    stem: "Correspondence is defined as a written communication distributed to:",
    choices: ["More than 25 retail investors", "25 or fewer retail investors in 30 days", "Institutional investors only", "Any number of investors"],
    answerIndex: 1,
    explanation: "Retail communication is the category above that threshold, and it carries the pre-approval requirement." },
  { id: "s7m-f1-002", examSlug: "series-7", topicId: "f1-business", topicName: "Seeks Business for the Broker-Dealer", difficulty: 2,
    stem: "A cold-calling representative must observe calling hours of:",
    choices: ["9am to 5pm for the client", "Any hour for the client", "8am to 9pm in the called party's time zone", "Only business hours locally in practice"],
    answerIndex: 2,
    explanation: "The rule uses the recipient's local time, not the caller's, and a firm-specific do-not-call list must be maintained." },
  { id: "s7m-f1-003", examSlug: "series-7", topicId: "f1-business", topicName: "Seeks Business for the Broker-Dealer", difficulty: 1,
    stem: "A prospect asking to be placed on the do-not-call list must be honoured for:",
    choices: ["30 days", "One year", "Indefinitely without record", "Five years"],
    answerIndex: 3,
    explanation: "The firm must maintain the record and honour the request across the firm rather than only for that representative." },
  { id: "s7m-f1-004", examSlug: "series-7", topicId: "f1-business", topicName: "Seeks Business for the Broker-Dealer", difficulty: 3,
    stem: "A registered representative may share in a customer's account profits and losses only if:",
    choices: ["Written consent and proportionate capital", "The customer agrees to it verbally", "The account has been profitable", "The firm is notified afterwards"],
    answerIndex: 0,
    explanation: "Both the customer's and the firm's written consent are required, and sharing must be proportionate to the representative's capital contribution." },
  { id: "s7m-f1-005", examSlug: "series-7", topicId: "f1-business", topicName: "Seeks Business for the Broker-Dealer", difficulty: 2,
    stem: "A representative offering a customer a gift valued at $250 has:",
    choices: ["Complied with the rule", "Exceeded the $100 annual gift limit", "Made a permitted business expense", "Triggered no requirement"],
    answerIndex: 1,
    explanation: "The FINRA gift limit is $100 per person per year; legitimate business entertainment is treated separately." },
  { id: "s7m-f1-006", examSlug: "series-7", topicId: "f1-business", topicName: "Seeks Business for the Broker-Dealer", difficulty: 1,
    stem: "An advertisement projecting future performance of a mutual fund is:",
    choices: ["Permitted with a disclaimer", "Required by the SEC", "Generally prohibited", "Permitted for institutions only"],
    answerIndex: 2,
    explanation: "Predictions and projections of performance are prohibited in retail communications, though hypothetical illustrations of mathematical principles may be permitted." },
  { id: "s7m-f1-007", examSlug: "series-7", topicId: "f1-business", topicName: "Seeks Business for the Broker-Dealer", difficulty: 2,
    stem: "A representative may describe a security as safe only when:",
    choices: ["The customer specifically asks for it", "The firm has approved the language", "Never, in writing or otherwise", "The claim is accurate and not misleading"],
    answerIndex: 3,
    explanation: "Standard practice and FINRA rules both prohibit exaggerated, unwarranted or misleading claims about any security." },
  { id: "s7m-f1-008", examSlug: "series-7", topicId: "f1-business", topicName: "Seeks Business for the Broker-Dealer", difficulty: 3,
    stem: "Testimonials in retail communications require disclosure that:",
    choices: ["It may not be typical, plus any payment", "Nothing further beyond the quote", "Only the date it was given", "Only the name of the firm"],
    answerIndex: 0,
    explanation: "If the testimonial concerns a technical matter, the maker's qualifications must also be disclosed." },
];

// ============================================================
// F2 — OPENS ACCOUNTS / FINANCIAL PROFILE (11, 9%)
// ============================================================
const F2: Question[] = [
  { id: "s7m-f2-000", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opens Accounts / Evaluates Financial Profile", difficulty: 1,
    stem: "A new account form for an individual must record the customer's identity, employment and:",
    choices: ["The customer's name only", "Objectives and financial profile", "The mailing address only", "The taxpayer number only"],
    answerIndex: 1,
    explanation: "The Customer Identification Program requires name, date of birth, address and identification number at a minimum." },
  { id: "s7m-f2-001", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opens Accounts / Evaluates Financial Profile", difficulty: 2,
    stem: "A customer refusing to provide financial information may:",
    choices: ["Not open an account for the client", "Open only a cash account for the client", "Still open an account, with the refusal documented", "Open only a margin account for the client"],
    answerIndex: 2,
    explanation: "The representative must document the refusal, and recommendations become harder to justify as suitable." },
  { id: "s7m-f2-002", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opens Accounts / Evaluates Financial Profile", difficulty: 2,
    stem: "A margin risk disclosure statement must be furnished to the customer:",
    choices: ["Only after the first margin call", "Once every three calendar years", "Only where the customer asks for it", "Before or when the account is opened"],
    answerIndex: 3,
    explanation: "The margin disclosure statement goes to the customer at or prior to account opening, and again annually thereafter." },
  { id: "s7m-f2-003", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opens Accounts / Evaluates Financial Profile", difficulty: 1,
    stem: "A joint account with rights of survivorship passes the deceased owner's interest to:",
    choices: ["The surviving owner", "The estate", "The named beneficiary", "The firm"],
    answerIndex: 0,
    explanation: "Tenants in common instead passes the deceased's share to their estate rather than to the co-owner." },
  { id: "s7m-f2-004", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opens Accounts / Evaluates Financial Profile", difficulty: 3,
    stem: "A transfer on death registration passes assets to:",
    choices: ["The estate through probate", "A named beneficiary outside probate", "The joint owner", "The firm"],
    answerIndex: 1,
    explanation: "It avoids probate for the registered assets without requiring a trust structure." },
  { id: "s7m-f2-005", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opens Accounts / Evaluates Financial Profile", difficulty: 3,
    stem: "Trading authorisation granted to a third party requires:",
    choices: ["Verbal instruction for the client", "Firm approval only for the client", "Written authorisation from the account owner", "No documentation for the client"],
    answerIndex: 2,
    explanation: "Full authorisation permits withdrawals; limited authorisation permits trading only." },
  { id: "s7m-f2-006", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opens Accounts / Evaluates Financial Profile", difficulty: 1,
    stem: "A discretionary account requires written authorisation and:",
    choices: ["No review", "Annual review only", "Customer approval per trade", "Prompt principal review of each order"],
    answerIndex: 3,
    explanation: "Discretion over time and price alone does not constitute discretionary authority requiring that documentation." },
  { id: "s7m-f2-007", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opens Accounts / Evaluates Financial Profile", difficulty: 2,
    stem: "An UTMA account's assets belong to:",
    choices: ["The minor, irrevocably", "The custodian", "The donor", "The firm"],
    answerIndex: 0,
    explanation: "The custodian manages the account, and only one custodian and one minor are permitted per account." },
  { id: "s7m-f2-008", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opens Accounts / Evaluates Financial Profile", difficulty: 3,
    stem: "Options accounts require the customer to receive the options disclosure document:",
    choices: ["Within 15 days after", "At or before account approval", "At the first trade", "Annually only"],
    answerIndex: 1,
    explanation: "The signed options agreement must be returned within 15 days of approval." },
  { id: "s7m-f2-009", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opens Accounts / Evaluates Financial Profile", difficulty: 1,
    stem: "A customer's investment objective of speculation would be inconsistent with a recommendation of:",
    choices: ["Uncovered option writing", "Aggressive growth stocks", "Investment grade bond funds", "Sector funds"],
    answerIndex: 2,
    explanation: "Suitability requires the recommendation to fit the stated objective, risk tolerance and financial situation together." },
  { id: "s7m-f2-010", examSlug: "series-7", topicId: "f2-accounts", topicName: "Opens Accounts / Evaluates Financial Profile", difficulty: 2,
    stem: "An account for an employee of another broker-dealer requires:",
    choices: ["No special handling of any kind", "Settlement in cash on every trade", "A signed margin agreement first", "Written notice to the employer"],
    answerIndex: 3,
    explanation: "Duplicate confirmations must be sent to the employing firm where it requests them." },
];

// ============================================================
// F3 — INFORMATION, RECOMMENDATIONS, RECORDS (91, 73%)
// ============================================================
const F3: Question[] = [
  { id: "s7m-f3a-000", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A customer buys 1 XYZ Oct 50 call at 4. The breakeven is:",
    choices: ["54", "46", "50", "44"],
    answerIndex: 0,
    explanation: "For a call the breakeven is strike plus premium; the maximum loss is the $400 premium paid." },
  { id: "s7m-f3a-001", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A customer writes 1 ABC Jan 30 put at 2. The maximum gain is:",
    choices: ["$2,800", "$200", "$3,200", "Unlimited"],
    answerIndex: 1,
    explanation: "The writer's maximum gain is the premium received; the maximum loss is the strike less the premium, times 100." },
  { id: "s7m-f3a-002", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "The maximum loss for the writer of that uncovered Jan 30 put at 2 is:",
    choices: ["$200", "$3,000", "$2,800", "Unlimited"],
    answerIndex: 2,
    explanation: "The stock can fall to zero, obliging the writer to buy at 30 having received only 2." },
  { id: "s7m-f3a-003", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A covered call writer's position is best described as:",
    choices: ["Unlimited upside participation", "No downside exposure at all", "A fully hedged position", "Capped upside, downside retained"],
    answerIndex: 3,
    explanation: "The premium cushions a small decline but does not protect against a large one." },
  { id: "s7m-f3a-004", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "A protective put buyer establishes:",
    choices: ["A floor at the strike less the premium", "Unlimited downside for the client", "A cap on gains for the client", "No position for the client"],
    answerIndex: 0,
    explanation: "It is the option analogue of insurance, and the premium is the cost of that protection." },
  { id: "s7m-f3a-005", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A customer long 100 shares at 42 buys 1 put with a 40 strike at 3. Maximum loss is:",
    choices: ["$300", "$500", "$4,200", "Unlimited"],
    answerIndex: 1,
    explanation: "The stock can fall to the 40 strike, a $200 loss, plus the $300 premium paid, for a maximum loss of $500." },
  { id: "s7m-f3a-006", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A long straddle profits when the underlying:",
    choices: ["Remains unchanged in practice", "Rises only for the client", "Moves sharply in either direction", "Falls only for the client"],
    answerIndex: 2,
    explanation: "The buyer needs a move exceeding the combined premiums to reach breakeven on either side." },
  { id: "s7m-f3a-007", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "A customer buys a call and a put on the same stock at the same strike and expiry. This is:",
    choices: ["A long combination", "A spread", "A collar", "A long straddle"],
    answerIndex: 3,
    explanation: "A combination uses different strikes or expiries; a straddle uses the same for both legs." },
  { id: "s7m-f3a-008", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "A debit call spread is established by:",
    choices: ["Buying the lower strike and selling the higher", "Selling the lower strike for the client", "Buying both strikes for the client", "Selling both strikes for the client"],
    answerIndex: 0,
    explanation: "The investor is moderately bullish, and both the cost and the maximum gain are capped." },
  { id: "s7m-f3a-009", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "The maximum gain on a debit call spread equals:",
    choices: ["The net debit for the client", "The strike difference less the net debit", "The strike difference for the client", "Unlimited for the client"],
    answerIndex: 1,
    explanation: "The maximum loss is the net debit paid, and both outcomes sum to the strike spread." },
  { id: "s7m-f3a-010", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A customer short 100 shares who writes a put has established:",
    choices: ["An uncovered put", "A straddle", "A covered put", "A collar"],
    answerIndex: 2,
    explanation: "The short stock position covers the obligation to buy if the put is exercised." },
  { id: "s7m-f3a-011", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "An option is in the money for the holder of a put when the market price is:",
    choices: ["Above the strike", "At the strike", "Irrelevant", "Below the strike"],
    answerIndex: 3,
    explanation: "A call is in the money when the market price exceeds the strike, which is the mirror relationship." },
  { id: "s7m-f3a-012", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "Time value of an option is greatest when the option is:",
    choices: ["At the money", "Deep in the money", "Deep out of the money", "At expiration"],
    answerIndex: 0,
    explanation: "Uncertainty about which side of the strike the option finishes on is what time value prices." },
  { id: "s7m-f3a-013", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "An American-style equity option may be exercised:",
    choices: ["Only at expiration", "Any time before expiration", "Only on the ex-date", "Only in the money"],
    answerIndex: 1,
    explanation: "Most listed index options are European style and may be exercised only at expiration." },
  { id: "s7m-f3a-014", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "Exercise of an equity option settles:",
    choices: ["In cash", "At the index level", "In the underlying shares", "Not at all"],
    answerIndex: 2,
    explanation: "Broad-based index options settle in cash rather than through delivery of a basket." },
  { id: "s7m-f3a-015", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A 5% stock dividend on an underlying adjusts an option contract by:",
    choices: ["Doing nothing to the contract", "Raising the strike price only", "Cancelling the contract outright", "Raising shares, cutting the strike"],
    answerIndex: 3,
    explanation: "A cash dividend does not adjust listed equity option contracts." },
  { id: "s7m-f3a-016", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "The Options Clearing Corporation functions as:",
    choices: ["Issuer and guarantor of listed options", "A broker-dealer for the client", "An exchange for the client", "A regulator for the client"],
    answerIndex: 0,
    explanation: "It stands between buyer and seller, which is what makes listed options fungible." },
  { id: "s7m-f3a-017", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A customer's uncovered call writing requires:",
    choices: ["No approval for the client", "The highest options approval level", "Level one approval in practice", "Cash account only in most cases"],
    answerIndex: 1,
    explanation: "Uncovered writing carries theoretically unlimited loss, which is why the approval requirement is strictest." },
  { id: "s7m-f3a-018", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "Municipal bond interest is generally exempt from:",
    choices: ["All taxes", "State tax everywhere", "Federal income tax", "Capital gains tax"],
    answerIndex: 2,
    explanation: "It is triple tax exempt only for a resident of the issuing state and municipality." },
  { id: "s7m-f3a-019", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "A general obligation bond is backed by:",
    choices: ["Revenue from a specific project", "A guarantee from the federal government", "Private bond insurance alone", "Full faith, credit and taxing power"],
    answerIndex: 3,
    explanation: "A revenue bond is instead payable only from the revenue of the specific facility financed." },
  { id: "s7m-f3a-020", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "A revenue bond's feasibility depends primarily on:",
    choices: ["The revenue of the financed project", "The issuer's tax base as stated", "Federal support for the client", "The general fund for the client"],
    answerIndex: 0,
    explanation: "Debt service coverage on that project revenue is the key analytical ratio." },
  { id: "s7m-f3a-021", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "The taxable equivalent yield of a 4% municipal bond for an investor in the 32% bracket is:",
    choices: ["2.72%", "5.88%", "4.00%", "12.50%"],
    answerIndex: 1,
    explanation: "Dividing the municipal yield by one minus the marginal rate produces the comparable taxable yield." },
  { id: "s7m-f3a-022", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "An investor in a low tax bracket comparing a 4% municipal with a 5.5% corporate should generally prefer:",
    choices: ["The municipal bond", "Either equally", "The corporate bond", "Neither"],
    answerIndex: 2,
    explanation: "The break-even tax rate determines the crossover, and low-bracket investors rarely benefit from municipals." },
  { id: "s7m-f3a-023", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "The Official Statement for a municipal issue is analogous to:",
    choices: ["A confirmation", "An account statement", "A subscription agreement", "A prospectus"],
    answerIndex: 3,
    explanation: "Municipal securities are exempt from Securities Act registration, so no formal prospectus is required." },
  { id: "s7m-f3a-024", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A municipal bond's yield to call is more relevant than yield to maturity when the bond trades:",
    choices: ["At a premium", "At a discount", "At par", "Below par"],
    answerIndex: 0,
    explanation: "Yield to worst is the conservative convention that takes the lower of the two." },
  { id: "s7m-f3a-025", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "Accrued interest on a corporate bond is calculated using:",
    choices: ["Actual/actual", "30/360", "Actual/360", "30/365"],
    answerIndex: 1,
    explanation: "Government bonds instead use actual/actual, which is the distinction most often tested." },
  { id: "s7m-f3a-026", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "Accrued interest on a Treasury note is calculated using:",
    choices: ["30/360", "Actual/360", "Actual/actual", "30/365"],
    answerIndex: 2,
    explanation: "Municipal bonds follow the corporate 30/360 convention rather than the government one." },
  { id: "s7m-f3a-027", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A Treasury STRIP is best described as:",
    choices: ["A coupon-bearing note for the client", "An agency security for the client", "A mortgage security for the client", "A zero-coupon obligation of the US government"],
    answerIndex: 3,
    explanation: "The investor faces phantom income taxable annually despite receiving no cash until maturity." },
  { id: "s7m-f3a-028", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "A GNMA pass-through security is backed by:",
    choices: ["The full faith and credit of the US government", "An implied guarantee only for the client", "State credit for the client", "Private insurance for the client"],
    answerIndex: 0,
    explanation: "FNMA and FHLMC carry an implied rather than an explicit federal guarantee." },
  { id: "s7m-f3a-029", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "The principal risk distinguishing mortgage securities from Treasuries is:",
    choices: ["Default risk", "Prepayment risk", "Currency risk", "Political risk"],
    answerIndex: 1,
    explanation: "Prepayments accelerate when rates fall, returning principal exactly when reinvestment is least attractive." },
  { id: "s7m-f3a-030", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A CMO tranche that receives principal first is the:",
    choices: ["Longest tranche as stated", "Residual tranche as stated", "Shortest average life tranche", "Support tranche as stated"],
    answerIndex: 2,
    explanation: "A planned amortisation class achieves stability by shifting prepayment variability onto support tranches." },
  { id: "s7m-f3a-031", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "An investor concerned about extension risk in a mortgage security fears that:",
    choices: ["Market rates subsequently fall", "Prepayments begin to accelerate", "Defaults in the pool rise", "Rising rates lengthen the security"],
    answerIndex: 3,
    explanation: "Contraction risk is the mirror problem when rates fall and prepayments speed up." },
  { id: "s7m-f3a-032", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "A corporate bond's indenture specifies:",
    choices: ["The terms and covenants of the issue", "The market price for the client", "The credit rating for the client", "The commission for the client"],
    answerIndex: 0,
    explanation: "A trustee is appointed to enforce the indenture on behalf of bondholders." },
  { id: "s7m-f3a-033", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "An equipment trust certificate is secured by:",
    choices: ["The issuer's general credit only", "Rolling stock pledged to a trustee", "A mortgage on the issuer's plant", "A guarantee from the parent firm"],
    answerIndex: 1,
    explanation: "Title to the equipment is held by a trustee until the certificates are retired, which makes it a secured obligation." },
  { id: "s7m-f3a-034", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A convertible bond's conversion ratio of 40 on a $1,000 par bond implies a conversion price of:",
    choices: ["$40", "$400", "$25", "$1,040"],
    answerIndex: 2,
    explanation: "Dividing par by the ratio gives the effective price paid per share on conversion." },
  { id: "s7m-f3a-035", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "That bond is at parity when the underlying stock trades at:",
    choices: ["Par", "The coupon rate", "The call price", "The conversion price"],
    answerIndex: 3,
    explanation: "Parity means the conversion value exactly equals the bond's market price." },
  { id: "s7m-f3a-036", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A preferred stock's dividend is:",
    choices: ["Fixed and paid before common dividends", "Variable", "Guaranteed", "Tax deductible to the issuer"],
    answerIndex: 0,
    explanation: "Cumulative preferred requires arrears to be cleared before any common dividend is paid." },
  { id: "s7m-f3a-037", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "An investor seeking current income with priority over common shareholders should consider:",
    choices: ["Common stock", "Preferred stock", "Warrants", "Rights"],
    answerIndex: 1,
    explanation: "The trade-off is limited participation in the company's growth." },
  { id: "s7m-f3a-038", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A rights offering gives existing shareholders:",
    choices: ["A long-dated option to buy", "A cash dividend payment", "A short-term subscription right", "An additional voting right"],
    answerIndex: 2,
    explanation: "Warrants are the long-dated equivalent, typically issued attached to another security." },
  { id: "s7m-f3a-039", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "An open-end investment company continuously:",
    choices: ["Trades on a stock exchange", "Maintains a fixed share count", "Trades at a discount to value", "Issues and redeems shares at NAV"],
    answerIndex: 3,
    explanation: "A closed-end fund has a fixed share count and trades at a market price that can differ from NAV." },
  { id: "s7m-f3a-040", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "A mutual fund's public offering price equals net asset value plus:",
    choices: ["Any sales charge", "The management fee", "The 12b-1 fee", "Nothing"],
    answerIndex: 0,
    explanation: "Forward pricing means the order is executed at the next computed NAV rather than the last one." },
  { id: "s7m-f3a-041", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A breakpoint in a mutual fund provides:",
    choices: ["A guaranteed rate of return", "A reduced load at higher amounts", "An additional dividend payment", "Redemption without any charge"],
    answerIndex: 1,
    explanation: "Failing to inform a customer approaching a breakpoint is a sales practice violation." },
  { id: "s7m-f3a-042", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A letter of intent allows an investor to obtain a breakpoint by:",
    choices: ["Investing the full amount at once", "Paying an administrative fee", "Committing to invest within 13 months", "Signing a binding contract"],
    answerIndex: 2,
    explanation: "It may be backdated up to 90 days to capture a recent purchase." },
  { id: "s7m-f3a-043", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "Class B mutual fund shares typically carry:",
    choices: ["A front-end sales load", "No sales charges at all", "A guaranteed rate of return", "A declining deferred sales charge"],
    answerIndex: 3,
    explanation: "Class A shares carry a front-end load with breakpoints; Class C carry a level load." },
  { id: "s7m-f3a-044", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "A variable annuity's separate account value is determined by:",
    choices: ["Investment performance of the subaccounts", "A guaranteed rate for the client", "The insurer's general account", "The prime rate for the client"],
    answerIndex: 0,
    explanation: "A fixed annuity instead pays from the insurer's general account at a guaranteed rate." },
  { id: "s7m-f3a-045", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A variable annuity is regulated as:",
    choices: ["Only insurance for the client", "Both a security and an insurance product", "Only a security for the client", "Neither for the client"],
    answerIndex: 1,
    explanation: "Selling one therefore requires both a securities registration and a state insurance licence." },
  { id: "s7m-f3a-046", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A 529 plan's earnings are federally tax free when used for:",
    choices: ["Any purpose in most cases", "Retirement for the client", "Qualified education expenses", "Medical costs in practice"],
    answerIndex: 2,
    explanation: "Non-qualified withdrawals attract income tax on earnings plus a penalty." },
  { id: "s7m-f3b-000", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A direct participation program passes through to investors:",
    choices: ["Income only for the client", "Losses only for the client", "Nothing for the client", "Income, gains, losses and deductions"],
    answerIndex: 3,
    explanation: "The flow-through of tax items is the defining feature of the partnership structure." },
  { id: "s7m-f3b-001", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A limited partner who takes an active management role risks:",
    choices: ["Losing the limited liability protection", "Higher depletion allowances only", "Automatic conversion to an S corp", "A mandatory partnership dissolution"],
    answerIndex: 0,
    explanation: "Participating in management can cause a limited partner to be treated as a general partner, with unlimited personal liability." },
  { id: "s7m-f3b-002", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A real estate investment trust must distribute at least:",
    choices: ["50% for the client", "90% of taxable income", "100% in most cases", "None in most cases"],
    answerIndex: 1,
    explanation: "Meeting that test allows the REIT to avoid taxation at the entity level." },
  { id: "s7m-f3b-003", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A REIT differs from a direct participation program in that it:",
    choices: ["Passes through losses", "Has no distributions", "Does not pass through losses", "Is not taxed"],
    answerIndex: 2,
    explanation: "That distinction is regularly tested because both are real-estate-related pass-through-sounding vehicles." },
  { id: "s7m-f3b-004", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "An exchange-traded fund's price is kept near net asset value by:",
    choices: ["The manager for the client", "The exchange for the client", "Regulation for the client", "Creation and redemption arbitrage"],
    answerIndex: 3,
    explanation: "Authorised participants exchange baskets of securities for fund shares, which closes any gap." },
  { id: "s7m-f3b-005", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A leveraged ETF's stated multiple applies over:",
    choices: ["One trading day", "One month", "One quarter", "One year"],
    answerIndex: 0,
    explanation: "Daily resetting makes longer holding period returns path dependent and usually worse." },
  { id: "s7m-f3b-006", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "Recommending a leveraged ETF as a long-term holding raises:",
    choices: ["No concern", "A suitability concern", "A disclosure issue only", "A pricing issue"],
    answerIndex: 1,
    explanation: "These are trading instruments whose multi-day behaviour differs from a long-horizon investor's expectation." },
  { id: "s7m-f3b-007", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A hedge fund is typically sold to:",
    choices: ["Any retail investor", "Only institutions", "Accredited or qualified investors", "Only foreign investors"],
    answerIndex: 2,
    explanation: "The private placement exemption is what limits the offering to that investor population." },
  { id: "s7m-f3b-008", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "Regulation D permits an issuer to sell securities without registration to:",
    choices: ["Anyone for the client", "Only institutions for the client", "Only foreign buyers for the client", "Accredited investors, subject to conditions"],
    answerIndex: 3,
    explanation: "Resale of the restricted securities is limited by Rule 144 holding periods." },
  { id: "s7m-f3b-009", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "Rule 144 governs the resale of:",
    choices: ["Restricted and control securities", "Any security", "Only registered shares", "Only municipal bonds"],
    answerIndex: 0,
    explanation: "The volume limitation is generally the greater of 1% of outstanding shares or the average weekly volume." },
  { id: "s7m-f3b-010", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "An affiliate selling restricted stock under Rule 144 must file:",
    choices: ["No filing of any kind", "Form 144 above the threshold", "An annual report on Form 10-K", "A full statutory prospectus"],
    answerIndex: 1,
    explanation: "The filing is required where the amount exceeds 5,000 shares or $50,000 in a three-month period." },
  { id: "s7m-f3b-011", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "Regulation A offerings are limited in size and provide:",
    choices: ["Full registration", "No disclosure", "A simplified registration path", "Bank-only distribution"],
    answerIndex: 2,
    explanation: "It is intended to lower the cost of capital raising for smaller issuers." },
  { id: "s7m-f3b-012", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A firm acting as principal in a trade:",
    choices: ["Acts purely as the client's agent", "Charges a commission on the trade", "Takes no position of its own", "Trades from its own inventory"],
    answerIndex: 3,
    explanation: "Acting as agent instead earns a commission and involves no inventory risk." },
  { id: "s7m-f3b-013", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A markup on a principal transaction must be:",
    choices: ["Fair and reasonable in the circumstances", "Exactly 5% for the client", "Any amount disclosed for the client", "Set by FINRA for the client"],
    answerIndex: 0,
    explanation: "The 5% policy is a guideline rather than a rule, and it does not apply to prospectus offerings." },
  { id: "s7m-f3b-014", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "The 5% policy does not apply to securities sold:",
    choices: ["Over the counter", "Under a prospectus", "On an exchange", "To institutions"],
    answerIndex: 1,
    explanation: "Mutual funds, variable annuities and new issues are priced by prospectus rather than by markup." },
  { id: "s7m-f3b-015", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A quotation showing a bid of 24.50 and an ask of 24.65 gives a spread of:",
    choices: ["24.50", "24.65", "15 cents", "49.15"],
    answerIndex: 2,
    explanation: "The customer buys at the ask and sells at the bid, which is how the dealer earns the spread." },
  { id: "s7m-f3b-016", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "A market order guarantees:",
    choices: ["Price but not execution", "Both", "Neither", "Execution but not price"],
    answerIndex: 3,
    explanation: "A limit order reverses the trade-off, guaranteeing price but not execution." },
  { id: "s7m-f3b-017", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A sell stop order is entered:",
    choices: ["Below the current market", "Above the market", "At the market", "At the open"],
    answerIndex: 0,
    explanation: "It becomes a market order once triggered, so the execution price is not guaranteed." },
  { id: "s7m-f3b-018", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A buy limit order is placed:",
    choices: ["Above the market", "Below the current market", "At the market", "At the close"],
    answerIndex: 1,
    explanation: "Buy stops and sell limits are placed above the market, which is the mirror arrangement." },
  { id: "s7m-f3b-019", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "An order marked all or none:",
    choices: ["May be partially filled as stated", "Executes immediately in most cases", "Must be filled entirely or not at all", "Expires daily for the client"],
    answerIndex: 2,
    explanation: "Fill or kill requires immediate complete execution; immediate or cancel permits a partial fill." },
  { id: "s7m-f3b-020", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "Regular way settlement for corporate and municipal securities is:",
    choices: ["T+2", "T+3", "Same day", "T+1"],
    answerIndex: 3,
    explanation: "The market moved to T+1 in May 2024, and government securities settle T+1 as well." },
  { id: "s7m-f3b-021", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "Regulation T payment is due from the customer within:",
    choices: ["Two business days after settlement", "Same day for the client", "Five days for the client", "Ten days for the client"],
    answerIndex: 0,
    explanation: "An extension may be requested where the customer has not paid by the deadline." },
  { id: "s7m-f3b-022", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "The Regulation T initial margin requirement is:",
    choices: ["25%", "50%", "30%", "100%"],
    answerIndex: 1,
    explanation: "Regulation T sets initial margin at 50% of the purchase price; FINRA's 25% maintenance minimum applies thereafter." },
  { id: "s7m-f3b-023", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A long margin account falls below the 25% maintenance level, triggering:",
    choices: ["A Regulation T call", "A frozen account", "A maintenance call", "No action"],
    answerIndex: 2,
    explanation: "The customer must deposit cash or securities to restore the required equity." },
  { id: "s7m-f3b-024", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A customer buying $40,000 of stock in a margin account must deposit:",
    choices: ["$10,000", "$40,000", "$2,000", "$20,000"],
    answerIndex: 3,
    explanation: "The Regulation T requirement is 50% of the purchase price for a marginable equity." },
  { id: "s7m-f3b-025", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "The minimum equity requirement to open a margin account is generally:",
    choices: ["$2,000", "$5,000", "$25,000", "$500"],
    answerIndex: 0,
    explanation: "FINRA requires $2,000 minimum equity to open a margin account; a pattern day trader is instead subject to $25,000." },
  { id: "s7m-f3b-026", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A pattern day trader's day-trading buying power is generally limited to:",
    choices: ["Two times the account's total equity", "Four times maintenance margin excess", "One times the account's total equity", "Six times maintenance margin excess"],
    answerIndex: 1,
    explanation: "The 4x limit applies to maintenance margin excess as of the prior day's close; exceeding it triggers a day-trading call." },
  { id: "s7m-f3b-027", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "Short selling requires the security to be:",
    choices: ["Owned by the seller", "In a cash account as stated", "Located and available to borrow", "Municipal for the client"],
    answerIndex: 2,
    explanation: "Short sales must be executed in a margin account rather than a cash account." },
  { id: "s7m-f3b-028", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "A short seller must pay the lender any:",
    choices: ["Interest on the sale proceeds", "Any capital gains realised", "Nothing beyond the borrow fee", "Dividends on the borrowed shares"],
    answerIndex: 3,
    explanation: "The lender remains entitled to the economics of ownership throughout the loan." },
  { id: "s7m-f3b-029", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A customer's short sale has a theoretically:",
    choices: ["Unlimited loss potential", "Capped loss", "Zero risk", "Guaranteed profit"],
    answerIndex: 0,
    explanation: "There is no ceiling on how far a share price can rise against the position." },
  { id: "s7m-f3b-030", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "Free-riding in a cash account occurs when a customer:",
    choices: ["Pays after the deadline passes", "Sells before paying for the buy", "Uses margin in a cash account", "Buys at the offered price"],
    answerIndex: 1,
    explanation: "The consequence is a 90-day freeze requiring cash in advance for subsequent purchases." },
  { id: "s7m-f3b-031", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "The account freeze following a free-riding violation lasts:",
    choices: ["30 days", "One year", "90 days", "Indefinitely"],
    answerIndex: 2,
    explanation: "During the freeze the customer must have cash in the account before any purchase." },
  { id: "s7m-f3b-032", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "A customer's confirmation must disclose whether the firm acted as:",
    choices: ["A market maker only", "An underwriter only", "A custodian", "Principal or agent"],
    answerIndex: 3,
    explanation: "The commission or markup and the settlement date must also appear." },
  { id: "s7m-f3b-033", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "A customer complaint received in writing must be:",
    choices: ["Recorded and given to a principal", "Ignored as a routine matter", "Handled verbally with the client", "Forwarded directly to the SEC"],
    answerIndex: 0,
    explanation: "Firms maintain a complaint file and report statistics to FINRA quarterly." },
  { id: "s7m-f3b-034", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "An unauthorised trade in a customer's non-discretionary account is:",
    choices: ["Permitted if profitable", "A serious sales practice violation", "Standard practice", "Allowed with later consent"],
    answerIndex: 1,
    explanation: "Subsequent ratification by the customer does not cure the original violation." },
  { id: "s7m-f3b-035", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "Churning is defined by:",
    choices: ["High commissions and nothing more", "Frequent contact with the client", "Excessive trading for the objectives", "Unusually large position sizes"],
    answerIndex: 2,
    explanation: "Control over the account and the volume relative to the objectives are the two elements assessed." },
  { id: "s7m-f3b-036", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "Selling away occurs when a representative:",
    choices: ["Sells to another firm's client in practice", "Sells at a discount for the client", "Sells short for the client", "Sells securities not offered through the firm"],
    answerIndex: 3,
    explanation: "Private securities transactions require written notice to and, where compensated, approval from the firm." },
  { id: "s7m-f3b-037", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A representative's outside business activity requires:",
    choices: ["Prior written notice to the firm", "No notice for the client", "SEC approval for the client", "Customer consent in practice"],
    answerIndex: 0,
    explanation: "The firm may impose conditions or prohibit the activity entirely." },
  { id: "s7m-f3b-038", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "Insider trading liability under the 1988 Act extends to:",
    choices: ["The trader only in practice", "Controlling persons of the firm", "The issuer only in practice", "Nobody else for the client"],
    answerIndex: 1,
    explanation: "Civil penalties can reach three times the profit gained or loss avoided." },
  { id: "s7m-f3b-039", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "Material non-public information may not be used or:",
    choices: ["Recorded", "Analysed", "Conveyed to others who trade", "Discussed internally"],
    answerIndex: 2,
    explanation: "Tipping carries liability for both the tipper and the tippee who trades on it." },
  { id: "s7m-f3b-040", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 3,
    stem: "Anti-money-laundering rules require a firm to file a suspicious activity report when:",
    choices: ["Any trade at all is executed", "The customer incurs a loss", "The customer files a complaint", "A transaction appears suspicious"],
    answerIndex: 3,
    explanation: "The customer must not be told that a report has been filed." },
  { id: "s7m-f3b-041", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A currency transaction report is required for cash transactions exceeding:",
    choices: ["$10,000 in a day", "$5,000", "$25,000", "$100,000"],
    answerIndex: 0,
    explanation: "Structuring transactions to avoid the threshold is itself a federal offence." },
  { id: "s7m-f3b-042", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 1,
    stem: "Regulation SHO's locate requirement obligates the firm to:",
    choices: ["Deliver the shares before the order", "Reasonably believe shares can be borrowed", "Obtain written consent from the issuer", "Settle every short sale in cash only"],
    answerIndex: 1,
    explanation: "A locate must be documented before a short sale order is accepted: reasonable grounds to believe the security can be borrowed and delivered by settlement." },
  { id: "s7m-f3b-043", examSlug: "series-7", topicId: "f3-recommend", topicName: "Provides Information, Makes Recommendations, Records", difficulty: 2,
    stem: "A customer's securities held in street name are registered in:",
    choices: ["The customer's own name", "The name of the issuer", "The broker-dealer's own name", "The transfer agent's name"],
    answerIndex: 2,
    explanation: "The customer remains the beneficial owner with all economic rights." },
];

// ============================================================
// F4 — PROCESSES AND CONFIRMS TRANSACTIONS (14, 11%)
// ============================================================
const F4: Question[] = [
  { id: "s7m-f4-000", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 1,
    stem: "A trade confirmation must be delivered to the customer:",
    choices: ["Within 30 days of the trade", "Once each calendar year", "Only where the client asks", "At or before completion"],
    answerIndex: 3,
    explanation: "Completion of the transaction means settlement for these purposes." },
  { id: "s7m-f4-001", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 3,
    stem: "Account statements must be sent to an active customer at least:",
    choices: ["Quarterly", "Monthly always", "Annually", "On request only"],
    answerIndex: 0,
    explanation: "Monthly statements are required in any month with activity in the account." },
  { id: "s7m-f4-002", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 2,
    stem: "A customer's order ticket must record the time of:",
    choices: ["Receipt only", "Receipt and execution", "Execution only", "Settlement"],
    answerIndex: 1,
    explanation: "The terms, the account and whether the order was solicited must also appear." },
  { id: "s7m-f4-003", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 1,
    stem: "An order marked unsolicited indicates the trade was:",
    choices: ["Recommended by the representative", "Discretionary", "Initiated by the customer", "Firm directed"],
    answerIndex: 2,
    explanation: "Marking a recommended trade unsolicited to avoid a suitability review is a serious violation." },
  { id: "s7m-f4-004", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 3,
    stem: "The ex-dividend date for a regular way trade is:",
    choices: ["Two days after the record date", "The date the dividend is paid", "The date of the declaration", "The day it trades without it"],
    answerIndex: 3,
    explanation: "Under T+1 settlement the ex-date and record date generally coincide." },
  { id: "s7m-f4-005", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 2,
    stem: "A customer buying stock on the ex-dividend date:",
    choices: ["Does not receive the declared dividend", "Receives the dividend in most cases", "Receives half for the client", "Must sell first for the client"],
    answerIndex: 0,
    explanation: "The price typically opens lower by approximately the dividend amount on that morning." },
  { id: "s7m-f4-006", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 1,
    stem: "When a stock splits two for one, the customer's position:",
    choices: ["Doubles in value for the client", "Doubles in shares and halves in price per share", "Halves in value for the client", "Is unchanged in shares for the client"],
    answerIndex: 1,
    explanation: "Total position value is unchanged, which is why a split creates nothing economically." },
  { id: "s7m-f4-007", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 2,
    stem: "A good til cancelled order left with the firm is typically:",
    choices: ["Cancelled monthly", "Executed at once", "Confirmed periodically with the customer", "Held indefinitely without review"],
    answerIndex: 2,
    explanation: "Firms confirm open orders periodically to ensure they still reflect the customer's intention." },
  { id: "s7m-f4-008", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 3,
    stem: "A customer's death requires the representative to:",
    choices: ["Continue trading as instructed", "Liquidate the account at once", "Transfer the assets to a spouse", "Cancel orders and freeze the account"],
    answerIndex: 3,
    explanation: "The firm requires a death certificate, letters testamentary and other documentation before acting." },
  { id: "s7m-f4-009", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 1,
    stem: "An ACAT transfer moves a customer's account:",
    choices: ["Between broker-dealers", "Between banks", "To the issuer", "To a trust"],
    answerIndex: 0,
    explanation: "The carrying firm must validate or take exception to the request within a specified period." },
  { id: "s7m-f4-010", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 2,
    stem: "A DK notice indicates a firm:",
    choices: ["Confirms the trade for the client", "Does not recognise the trade as described", "Rejects settlement for the client", "Accepts delivery for the client"],
    answerIndex: 1,
    explanation: "It initiates a reconciliation process between the two firms before settlement fails." },
  { id: "s7m-f4-011", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 2,
    stem: "Good delivery of a stock certificate requires:",
    choices: ["Any condition for the client", "A prospectus for the client", "Proper endorsement and negotiable form", "A confirmation only for the client"],
    answerIndex: 2,
    explanation: "Certificates are now largely book-entry, which has reduced the practical relevance of the rules." },
  { id: "s7m-f4-012", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 1,
    stem: "A customer's securities may be commingled with firm assets:",
    choices: ["Always", "With consent", "In margin accounts", "Never"],
    answerIndex: 3,
    explanation: "Segregation of fully paid customer securities is a fundamental customer protection requirement." },
  { id: "s7m-f4-013", examSlug: "series-7", topicId: "f4-process", topicName: "Processes and Confirms Transactions", difficulty: 2,
    stem: "Excess margin securities are:",
    choices: ["Segregated from firm holdings", "Freely lendable by the firm", "Treated as firm property", "Sold as soon as possible"],
    answerIndex: 0,
    explanation: "The firm may hypothecate up to 140% of the customer's debit balance." },
];

export const S7_MOCK_FULL: Question[] = [...F1, ...F2, ...F3, ...F4];

// Blueprint-weighted 15-question readiness sample: 1 F1, 1 F2, 11 F3, 2 F4
export const S7_MOCK_QUICK: Question[] = [
  F1[0], F2[0],
  F3[0], F3[8], F3[16], F3[24], F3[32], F3[40], F3[48], F3[56], F3[64], F3[72], F3[80],
  F4[0], F4[7],
];

export const S7_FULL_READY = true;
