// ============================================================
// Certus — SIE Full Mock Exam bank
// ORIGINAL questions written to the FINRA SIE content outline.
// Reserved for the mock; never appear in practice drills, so a
// sitting is always "unseen."
//
// Authenticity (match — or beat — the real exam):
//   · Exactly 4 answer choices (A/B/C/D) — real SIE format
//   · 75 scored questions, one 1 h 45 m session, ~84 s/question
//   · Blueprint weights: Capital Markets 16% (12), Products 44% (33),
//     Trading & Accounts 31% (23), Regulatory 9% (7)
//   · Stems use "EXCEPT / NOT / least likely / most likely"
//   · Current rules: T+1 settlement (since May 2024)
//
// SIE_MOCK_FULL  — the 75-question sit-down exam
// SIE_MOCK_QUICK — a 15-question blueprint-weighted readiness sample
// ============================================================

import { Question } from "./types";

const q = (
  id: string,
  topicId: string,
  topicName: string,
  difficulty: 1 | 2 | 3,
  stem: string,
  choices: string[],
  answerIndex: number,
  explanation: string
): Question => ({ id, examSlug: "sie", topicId, topicName, difficulty, stem, choices, answerIndex, explanation });

const CM = "capital-markets", CMN = "Capital Markets";
const PR = "products", PRN = "Products & Their Risks";
const TA = "trading-accounts", TAN = "Trading & Accounts";
const RG = "regulatory", RGN = "Regulatory Framework";

// ============================================================
// SECTION 1 — KNOWLEDGE OF CAPITAL MARKETS (12 questions, ~16%)
// ============================================================
const SEC1: Question[] = [
  q("sm-cm1", CM, CMN, 2, "Each of the following is a self-regulatory organization (SRO) EXCEPT:", ["FINRA", "The Cboe", "The MSRB", "The SEC"], 3, "The SEC is a federal government agency, not an SRO. SROs (FINRA, the Cboe, the MSRB) are industry bodies that write and enforce rules under the SEC's oversight."),
  q("sm-cm2", CM, CMN, 2, "A Treasury bill is best described as a security that:", ["Pays semiannual interest and matures in 2–10 years", "Is issued at a discount and pays no periodic interest", "Is backed only by the revenue of a specific project", "Adjusts its principal for inflation"], 1, "T-bills are issued at a discount to face value, mature in one year or less, and pay no coupon — the return is the difference between the discounted purchase price and par."),
  q("sm-cm3", CM, CMN, 2, "When a corporation sells newly issued shares to the public and receives the proceeds, the transaction occurs in the:", ["Secondary market", "Third market", "Primary market", "Fourth market"], 2, "The primary market is where issuers sell new securities and receive the proceeds. Once those shares trade between investors, they trade in the secondary market."),
  q("sm-cm4", CM, CMN, 2, "The Federal Reserve's most frequently used tool for conducting monetary policy is:", ["Changing the reserve requirement", "Changing the discount rate", "Open market operations", "Setting margin requirements"], 2, "Open market operations — buying or selling Treasury securities — is the Fed's most-used and most flexible tool. Buying injects money and lowers rates; selling does the opposite."),
  q("sm-cm5", CM, CMN, 3, "Which of the following is considered a LAGGING economic indicator?", ["Stock prices", "Building permits", "New orders for durable goods", "The unemployment rate"], 3, "Unemployment turns after the economy does, making it a lagging indicator. Stock prices, building permits, and new orders are leading indicators that turn before the broader economy."),
  q("sm-cm6", CM, CMN, 2, "A recession is most commonly defined as:", ["A single quarter of declining GDP", "Two consecutive quarters of declining real GDP", "Any quarter in which unemployment rises", "A decline in the stock market of 20% or more"], 1, "The classic shorthand for a recession is two consecutive quarters of declining real GDP. A prolonged, severe version is a depression."),
  q("sm-cm7", CM, CMN, 2, "The New York Stock Exchange is best characterized as which type of market?", ["A negotiated, dealer market", "An auction market", "An over-the-counter market", "An electronic communications network only"], 1, "The NYSE is an auction market where buyers and sellers compete with bids and offers. The over-the-counter (Nasdaq) market is a negotiated dealer market."),
  q("sm-cm8", CM, CMN, 3, "In a firm-commitment underwriting, the risk of unsold shares is borne by the:", ["Issuer", "Underwriter", "Transfer agent", "SEC"], 1, "In a firm commitment the underwriter buys the entire issue as principal and bears the risk of any unsold shares. In a best-efforts deal the underwriter acts as agent and the issuer bears that risk."),
  q("sm-cm9", CM, CMN, 2, "During the cooling-off period of a new issue, a registered representative may:", ["Accept a binding sale from a customer", "Send a customer the final prospectus", "Distribute a preliminary prospectus (red herring)", "Guarantee the offering price"], 2, "During the 20-day cooling-off period, sales are prohibited; reps may only take indications of interest and distribute the preliminary prospectus (red herring). The final prospectus comes at the effective date."),
  q("sm-cm10", CM, CMN, 2, "As prevailing interest rates rise, the price of an outstanding fixed-rate bond will most likely:", ["Rise", "Fall", "Remain unchanged", "Move to par immediately"], 1, "Bond prices move inversely to interest rates. When rates rise, existing lower-coupon bonds become less attractive and their prices fall to a discount."),
  q("sm-cm11", CM, CMN, 3, "The Municipal Securities Rulemaking Board (MSRB) writes rules for municipal securities dealers but:", ["Also enforces those rules against bank dealers itself", "Has no enforcement arm; enforcement is done by FINRA and the SEC", "Regulates the issuers of municipal bonds", "Registers municipal representatives with the states"], 1, "The MSRB writes rules but has no enforcement authority. Its rules are enforced by FINRA (for broker-dealers) and bank regulators/the SEC. The MSRB also cannot regulate issuers."),
  q("sm-cm12", CM, CMN, 3, "An inverted yield curve, in which short-term rates exceed long-term rates, is most often viewed as a signal of:", ["Accelerating economic expansion", "An approaching economic slowdown or recession", "Rising inflation expectations", "A stable, neutral economy"], 1, "An inverted (downward-sloping) yield curve has historically preceded economic slowdowns and recessions. A normal, upward-sloping curve is typical of expansion."),
];

// ============================================================
// SECTION 2 — UNDERSTANDING PRODUCTS AND THEIR RISKS (33, ~44%)
// ============================================================
const SEC2: Question[] = [
  q("sm-pr1", PR, PRN, 2, "In a corporate liquidation, which party has the LAST claim on assets?", ["Secured bondholders", "General creditors", "Preferred stockholders", "Common stockholders"], 3, "Common stockholders have the residual, last-in-line claim — paid only after secured creditors, general creditors, and preferred stockholders. In exchange they capture the unlimited upside."),
  q("sm-pr2", PR, PRN, 2, "A feature of cumulative preferred stock is that:", ["It can be exchanged for a fixed number of common shares", "Skipped dividends accrue and must be paid before any common dividend", "It always pays a dividend higher than the stated rate", "It carries full voting rights"], 1, "Cumulative preferred accrues any skipped (in-arrears) dividends, all of which must be paid before common shareholders receive anything. Convertible preferred is exchangeable for common; participating can pay extra."),
  q("sm-pr3", PR, PRN, 2, "Preferred stock is most sensitive to changes in:", ["The issuer's revenue growth", "Interest rates", "The common stock's dividend", "Trading volume"], 1, "Because preferred pays a fixed dividend, it behaves like a fixed-income security and is sensitive to interest rates — when rates rise, preferred prices generally fall."),
  q("sm-pr4", PR, PRN, 3, "Which statement about rights and warrants is CORRECT?", ["Rights are long-term; warrants are short-term", "Rights are issued above market; warrants below", "Rights are short-term and priced below market; warrants are long-term and priced above market at issue", "Both are always attached to preferred stock"], 2, "Rights are short-term (weeks) and let existing shareholders buy new shares below market. Warrants are long-term (years), usually a sweetener attached to bonds, with an exercise price above the market at issuance."),
  q("sm-pr5", PR, PRN, 2, "An American Depositary Receipt (ADR) is used to:", ["Let U.S. investors trade foreign company shares in U.S. markets", "Guarantee a fixed rate of return on a foreign bond", "Convert a bond into common stock", "Provide voting control of a foreign issuer"], 0, "ADRs represent shares of a foreign company, trade in U.S. markets in U.S. dollars, and let U.S. investors gain foreign exposure. Holders still bear currency risk."),
  q("sm-pr6", PR, PRN, 2, "One option contract typically represents how many shares of the underlying stock?", ["1", "10", "100", "1,000"], 2, "A standard listed equity option covers 100 shares. A premium quoted at 3 therefore costs $300 for one contract."),
  q("sm-pr7", PR, PRN, 3, "An investor buys 1 XYZ 50 call at a premium of 4. The breakeven at expiration is:", ["$46", "$50", "$54", "$58"], 2, "A long call's breakeven is the strike plus the premium: 50 + 4 = $54. 'Call up, put down' — a call breaks even above the strike by the premium paid."),
  q("sm-pr8", PR, PRN, 2, "The maximum loss to the buyer of a call option is:", ["Unlimited", "The strike price", "The premium paid", "The strike minus the premium"], 2, "A long option buyer can lose no more than the premium paid — if the option expires out of the money, it simply expires worthless."),
  q("sm-pr9", PR, PRN, 2, "A long put position is:", ["Bullish", "Bearish", "Neutral", "Only used to hedge bonds"], 1, "Buying a put is bearish — the holder profits if the stock falls, gaining the right to sell at the strike above the market price."),
  q("sm-pr10", PR, PRN, 3, "An investor who owns stock and buys a put on that stock has established a:", ["Covered call", "Protective put", "Long straddle", "Credit spread"], 1, "Long stock plus a long put is a protective put — portfolio insurance that caps the downside at the strike while leaving the upside open, at the cost of the premium."),
  q("sm-pr11", PR, PRN, 3, "Which Treasury security adjusts its principal for inflation?", ["Treasury bills", "STRIPS", "TIPS", "Treasury bonds"], 2, "TIPS (Treasury Inflation-Protected Securities) adjust principal with the CPI, and the fixed coupon applies to the adjusted principal — protecting purchasing power. STRIPS are zero-coupon Treasuries."),
  q("sm-pr12", PR, PRN, 2, "Interest earned on U.S. Treasury securities is:", ["Exempt from all taxes", "Taxable at the federal level but exempt from state and local tax", "Exempt from federal tax but taxable by states", "Taxable at every level"], 1, "Treasury interest is subject to federal income tax but exempt from state and local taxes — the reverse of a municipal bond, whose interest is generally federally tax-free."),
  q("sm-pr13", PR, PRN, 2, "Interest from a general obligation municipal bond is generally:", ["Fully taxable", "Exempt from federal income tax", "Exempt from state tax only", "Subject to a flat 15% rate"], 1, "Municipal bond interest is generally exempt from federal income tax (and from state tax if the investor lives in the issuing state), which is why high-bracket investors favor munis."),
  q("sm-pr14", PR, PRN, 3, "A general obligation (GO) bond is backed by:", ["The revenue of a specific project", "The full faith, credit, and taxing power of the issuer", "A private corporation's guarantee", "The federal government"], 1, "GO bonds are backed by the issuer's full faith, credit, and taxing power and usually require voter approval. Revenue bonds are backed only by a specific project's revenues."),
  q("sm-pr15", PR, PRN, 2, "A corporate bond backed only by the general credit of the issuer, with no specific collateral, is a:", ["Mortgage bond", "Equipment trust certificate", "Debenture", "Collateral trust bond"], 2, "A debenture is an unsecured corporate bond backed only by the issuer's general creditworthiness. Mortgage bonds and equipment trust certificates are secured by specific assets."),
  q("sm-pr16", PR, PRN, 3, "Which U.S. agency security is backed by the full faith and credit of the U.S. government?", ["Fannie Mae (FNMA)", "Freddie Mac (FHLMC)", "Ginnie Mae (GNMA)", "The Federal Home Loan Banks"], 2, "Ginnie Mae (GNMA) is the only one of these backed by the full faith and credit of the U.S. government. Fannie Mae and Freddie Mac are government-sponsored enterprises without that explicit guarantee."),
  q("sm-pr17", PR, PRN, 2, "A money market instrument is best described as:", ["A long-term equity security", "A short-term, high-quality debt instrument", "A derivative on interest rates", "A pooled real estate investment"], 1, "Money market instruments (T-bills, commercial paper, negotiable CDs, banker's acceptances) are short-term (one year or less), high-quality debt used for liquidity and capital preservation."),
  q("sm-pr18", PR, PRN, 2, "Shares of an open-end mutual fund are:", ["Traded on an exchange throughout the day", "Priced continuously by supply and demand", "Redeemable with the fund at the next computed NAV (forward pricing)", "Issued in a fixed number that never changes"], 2, "Open-end fund shares are bought from and redeemed by the fund itself at the next computed NAV (forward pricing). The fund issues an unlimited number of shares; it is not exchange-traded."),
  q("sm-pr19", PR, PRN, 3, "A mutual fund's public offering price (POP) equals:", ["NAV minus the sales charge", "NAV plus the sales charge", "NAV divided by shares outstanding", "The bid price plus a markup"], 1, "For a front-load fund, POP = NAV + sales charge. The maximum sales charge permitted by FINRA is 8.5% of the POP."),
  q("sm-pr20", PR, PRN, 2, "Compared with a mutual fund, an exchange-traded fund (ETF):", ["Can only be redeemed once per day at NAV", "Trades intraday on an exchange at market prices", "Is always actively managed", "Cannot be bought on margin"], 1, "ETFs trade intraday on an exchange at market-determined prices (which can differ slightly from NAV), can be bought on margin, and are often index-based — unlike a mutual fund's once-daily NAV redemption."),
  q("sm-pr21", PR, PRN, 3, "A unit investment trust (UIT) is characterized by:", ["An actively managed, changing portfolio", "A fixed portfolio held to a set termination date, with redeemable units", "Continuous issuance of new shares at NAV plus a load", "Trading at a premium or discount to NAV on an exchange"], 1, "A UIT holds a fixed, unmanaged portfolio to a stated termination date and issues redeemable units. It is not actively managed and does not continuously trade like a closed-end fund."),
  q("sm-pr22", PR, PRN, 3, "A closed-end fund differs from an open-end fund in that its shares:", ["Are always redeemed at NAV", "Trade on an exchange and may sell at a premium or discount to NAV", "Cannot be sold short", "Are priced only once per day at NAV"], 1, "Closed-end funds issue a fixed number of shares that then trade on an exchange at a market price, which can be above (premium) or below (discount) NAV — unlike open-end funds, which transact at NAV."),
  q("sm-pr23", PR, PRN, 2, "A variable annuity differs from a fixed annuity because the variable annuity:", ["Guarantees a minimum rate of return", "Places the investment risk on the insurance company", "Invests in a separate account and passes investment risk to the owner", "Is not considered a security"], 2, "A variable annuity's premiums go into a separate account of sub-accounts; the owner bears the investment risk, and the product is a security requiring a prospectus. A fixed annuity guarantees a rate and is insurance."),
  q("sm-pr24", PR, PRN, 3, "A real estate investment trust (REIT):", ["Passes through both income and losses to investors", "Must distribute at least 90% of its taxable income to avoid corporate tax", "Is a limited partnership interest", "Is federally guaranteed"], 1, "A REIT must distribute at least 90% of taxable income to shareholders to receive favorable tax treatment. Unlike a DPP, a REIT does NOT pass losses through to investors."),
  q("sm-pr25", PR, PRN, 3, "A distinguishing feature of a direct participation program (DPP) is that it:", ["Is highly liquid and exchange-traded", "Passes through income and losses directly to investors", "Guarantees a fixed return", "Is exempt from suitability requirements"], 1, "DPPs (limited partnerships) pass through income AND losses directly to investors. They are illiquid, carry high suitability standards, and offer no guaranteed return."),
  q("sm-pr26", PR, PRN, 2, "The risk that a security cannot be sold quickly without a significant price concession is:", ["Market risk", "Liquidity risk", "Interest-rate risk", "Reinvestment risk"], 1, "Liquidity (marketability) risk is the risk of not being able to sell an investment quickly at a fair price. DPPs and thinly traded securities carry high liquidity risk."),
  q("sm-pr27", PR, PRN, 3, "Systematic risk is best described as:", ["Risk unique to a single company that can be diversified away", "Market-wide risk that cannot be eliminated through diversification", "The risk that a bond issuer defaults", "The risk of a company's management making poor decisions"], 1, "Systematic (market) risk affects the whole market and cannot be diversified away. Unsystematic (company-specific) risk can be reduced by holding a diversified portfolio."),
  q("sm-pr28", PR, PRN, 2, "The risk that inflation erodes the purchasing power of a fixed stream of interest payments is called:", ["Credit risk", "Purchasing-power risk", "Call risk", "Legislative risk"], 1, "Purchasing-power (inflation) risk is greatest for long-term fixed-income securities, whose fixed payments buy less as prices rise."),
  q("sm-pr29", PR, PRN, 3, "Call risk on a bond is the risk that:", ["The issuer defaults on interest", "The issuer redeems the bond early, forcing reinvestment at lower rates", "Interest rates rise and the price falls", "The bond cannot be sold"], 1, "Call risk is the risk that an issuer redeems a callable bond early — typically when rates have fallen — leaving the investor to reinvest the proceeds at lower prevailing rates."),
  q("sm-pr30", PR, PRN, 2, "A bond rated below investment grade (e.g., BB or lower) is best described as:", ["A guaranteed-income security", "A high-yield or 'junk' bond with elevated default risk", "A tax-free municipal", "A money market instrument"], 1, "Below-investment-grade bonds (BB+/Ba1 and lower) are high-yield or 'junk' bonds — they offer higher yields to compensate for greater credit (default) risk."),
  q("sm-pr31", PR, PRN, 3, "For a bond trading at a discount, which yield is the HIGHEST?", ["Nominal (coupon) yield", "Current yield", "Yield to maturity", "They are all equal"], 2, "For a discount bond the ranking is nominal < current < yield to maturity < yield to call. The pull toward par at maturity makes YTM the highest of the standard yields."),
  q("sm-pr32", PR, PRN, 2, "Commercial paper is:", ["A long-term secured corporate bond", "Short-term unsecured corporate debt issued at a discount", "A municipal revenue bond", "A type of preferred stock"], 1, "Commercial paper is short-term (270 days or less), unsecured corporate debt issued at a discount to raise working capital. Its short maturity keeps it exempt from Securities Act registration."),
  q("sm-pr33", PR, PRN, 3, "A customer seeking maximum safety of principal and immediate liquidity would be BEST suited by:", ["A high-yield corporate bond fund", "A money market fund", "A variable annuity", "A DPP"], 1, "A money market fund emphasizes preservation of principal and liquidity, aiming to maintain a stable value. High-yield funds, variable annuities, and DPPs all carry materially more risk or illiquidity."),
];

// ============================================================
// SECTION 3 — TRADING, CUSTOMER ACCOUNTS & PROHIBITED ACTIVITIES (23, ~31%)
// ============================================================
const SEC3: Question[] = [
  q("sm-ta1", TA, TAN, 2, "A market order to buy is executed:", ["Only at the customer's specified price or better", "Immediately at the best available price", "Only at the close of trading", "When the stock reaches a trigger price"], 1, "A market order executes immediately at the best available price — it prioritizes speed of execution over price. A limit order prioritizes price and may not fill."),
  q("sm-ta2", TA, TAN, 3, "A limit order guarantees:", ["Execution, but not price", "Price, but not execution", "Both price and execution", "Neither price nor execution"], 1, "A limit order fills only at the customer's limit price or better, so the price is controlled — but there is no guarantee it executes at all if the market never reaches the limit."),
  q("sm-ta3", TA, TAN, 3, "A buy stop order becomes a market order when the stock:", ["Falls to or below the stop price", "Rises to or through the stop price", "Reaches the prior day's close", "Pays a dividend"], 1, "A buy stop is placed above the current market and is triggered when the price rises to or through the stop — commonly used to protect a short position or to buy on upside momentum."),
  q("sm-ta4", TA, TAN, 2, "Regular-way settlement for a common stock transaction is:", ["Same day (T+0)", "One business day after the trade (T+1)", "Two business days after the trade (T+2)", "Three business days after the trade (T+3)"], 1, "Regular-way settlement for equities, corporate bonds, and municipal securities is T+1 (one business day after the trade), effective since May 2024. Options and Treasuries settle T+1 as well."),
  q("sm-ta5", TA, TAN, 3, "In a joint tenants with right of survivorship (JTWROS) account, when one owner dies, that owner's interest passes to:", ["The deceased owner's estate", "The surviving tenant(s)", "The broker-dealer", "The state"], 1, "In a JTWROS account, a deceased owner's interest passes directly to the surviving tenant(s). In a tenants-in-common (TIC) account, that interest passes to the decedent's estate."),
  q("sm-ta6", TA, TAN, 3, "An UGMA/UTMA custodial account may have:", ["Multiple minors and one custodian", "One minor and one custodian", "One minor and joint custodians", "Multiple custodians and multiple minors"], 1, "An UGMA/UTMA account has exactly one minor and one custodian. Gifts into the account are irrevocable and belong to the minor, who gains control at the age of majority."),
  q("sm-ta7", TA, TAN, 3, "A registered representative may exercise discretion in a customer's account only after:", ["Receiving a verbal instruction for each trade", "Obtaining prior written authorization from the customer", "The account has been open for 30 days", "The customer reaches age 59½"], 1, "Discretionary trading requires prior written authorization (a signed power of attorney) and firm approval. Deciding the amount, price, or timing of an otherwise-specified order is not discretion."),
  q("sm-ta8", TA, TAN, 2, "Under Regulation T, the initial margin requirement to buy stock is:", ["25% of market value", "30% of market value", "50% of market value", "100% of market value"], 2, "Regulation T sets the initial margin requirement at 50% of the purchase's market value. FINRA's minimum maintenance requirement (25% long) applies after the position is established."),
  q("sm-ta9", TA, TAN, 3, "Effecting excessive trades in a customer's account primarily to generate commissions is:", ["Front-running", "Churning", "Painting the tape", "Backing away"], 1, "Churning is excessive trading driven by the rep's interest in commissions rather than the customer's objectives — a prohibited practice and a violation of the duty of fair dealing."),
  q("sm-ta10", TA, TAN, 3, "A representative who enters a personal order ahead of a customer's known large block order is engaging in:", ["Front-running", "Churning", "Selling away", "Freeriding"], 0, "Front-running is trading for one's own (or the firm's) account ahead of a known, imminent customer block order to profit from its expected market impact — a prohibited practice."),
  q("sm-ta11", TA, TAN, 2, "Trading on material, nonpublic information about a company is:", ["Permitted if the rep is licensed", "Insider trading, which is prohibited", "Allowed after market close", "Permitted for institutional accounts only"], 1, "Trading on material nonpublic information — or tipping others who trade on it — is insider trading, prohibited under the Securities Exchange Act of 1934 with severe civil and criminal penalties."),
  q("sm-ta12", TA, TAN, 3, "Entering matched buy and sell orders to create the false appearance of active trading is known as:", ["Painting the tape", "Dollar-cost averaging", "A protective put", "Rebalancing"], 0, "Painting the tape (a form of matched orders) is market manipulation — creating a misleading impression of trading activity to lure other investors. It is strictly prohibited."),
  q("sm-ta13", TA, TAN, 3, "A registered representative sells a private investment to a customer without the knowledge or approval of the employing firm. This prohibited practice is:", ["Selling away", "Churning", "Front-running", "Breakpoint selling"], 0, "Selling away is participating in a private securities transaction outside the scope of employment without the firm's prior written approval — prohibited under FINRA rules."),
  q("sm-ta14", TA, TAN, 2, "Under a firm's anti-money-laundering program, the Customer Identification Program (CIP) requires the firm to:", ["Report all trades to the IRS", "Verify the identity of each customer opening an account", "Guarantee the source of a customer's funds", "Approve every transaction with a principal"], 1, "The CIP, part of the required AML program, obligates firms to collect and verify identifying information (name, DOB, address, SSN/TIN) for each customer opening an account."),
  q("sm-ta15", TA, TAN, 3, "A firm must file a Currency Transaction Report (CTR) when a customer conducts a cash transaction exceeding:", ["$3,000", "$5,000", "$10,000", "$50,000"], 2, "A CTR is required for cash transactions exceeding $10,000 in a single day. A Suspicious Activity Report (SAR) is filed for suspicious activity regardless of the dollar amount (generally $5,000+ for SARs)."),
  q("sm-ta16", TA, TAN, 3, "Regulation Best Interest (Reg BI) requires that when a broker-dealer makes a recommendation to a retail customer, it must act in the customer's:", ["Best interest, without placing its own interests ahead of the customer's", "Interest only if the customer is an accredited investor", "Interest only for fee-based accounts", "Interest as measured solely by past performance"], 0, "Reg BI requires a broker-dealer to act in the retail customer's best interest at the time of a recommendation and not place its own financial interests ahead of the customer's, satisfying disclosure, care, conflict, and compliance obligations."),
  q("sm-ta17", TA, TAN, 2, "FINRA's Know Your Customer rule requires a firm to use reasonable diligence to know the essential facts about:", ["Only the firm's largest accounts", "Every customer and the authority of anyone acting on the account", "Only margin accounts", "Only institutional customers"], 1, "The Know Your Customer rule (FINRA 2090) requires reasonable diligence to know and retain the essential facts about every customer and the authority of each person acting on that customer's behalf."),
  q("sm-ta18", TA, TAN, 3, "A customer wants to open a numbered account (identified by a number rather than a name). This is:", ["Prohibited in all cases", "Permitted if the customer signs a written statement attesting to ownership", "Permitted only for institutional accounts", "Permitted only with SEC approval"], 1, "Numbered accounts are permitted provided the firm keeps a signed written statement from the customer attesting to ownership. The customer's true identity must still be known to the firm."),
  q("sm-ta19", TA, TAN, 3, "Upon learning of the death of an individual account holder, a registered representative should FIRST:", ["Liquidate the account immediately", "Cancel all open orders and freeze the account pending documents", "Transfer the assets to the next of kin", "Continue trading per the last instructions"], 1, "At notice of a customer's death, the rep should cancel all open orders and freeze the account, then await the required legal documents (death certificate, court appointments) before taking further action."),
  q("sm-ta20", TA, TAN, 2, "A trade confirmation must be delivered to the customer:", ["Within 30 days of the trade", "At or before the completion of the transaction (settlement)", "Only upon customer request", "At the end of the calendar quarter"], 1, "A confirmation disclosing the trade details must be delivered at or before the completion of the transaction (settlement date). Account statements are generally sent at least quarterly."),
  q("sm-ta21", TA, TAN, 3, "Charging a customer an unfairly high markup on a principal (dealer) transaction violates:", ["The 5% policy / fair-pricing rules", "Regulation T", "The prospectus delivery rule", "The penny stock rule"], 0, "FINRA's 5% policy is a guideline (not a hard cap) requiring markups, markdowns, and commissions to be fair and reasonable. Excessive markups on principal trades violate fair-pricing rules."),
  q("sm-ta22", TA, TAN, 2, "Which account registration allows two owners to each own a specified fractional interest that passes to their estate at death?", ["Joint tenants with right of survivorship", "Tenants in common", "Custodial (UTMA)", "Transfer on death"], 1, "Tenants in common (TIC) lets owners hold unequal, specified fractional interests; at death, an owner's share passes to that owner's estate rather than to the surviving owner(s)."),
  q("sm-ta23", TA, TAN, 3, "A registered representative accepts an order from the customer's spouse, who is not named on the account and has no written authorization. The representative should:", ["Enter the order because the spouse is family", "Refuse the order absent proper written third-party authorization", "Enter the order but mark it unsolicited", "Enter the order only if it is a sale"], 1, "Only the account owner (or a properly authorized third party with written authorization on file) may direct activity in an account. Without that authorization, the rep must not accept the spouse's order."),
];

// ============================================================
// SECTION 4 — OVERVIEW OF THE REGULATORY FRAMEWORK (7, ~9%)
// ============================================================
const SEC4: Question[] = [
  q("sm-rg1", RG, RGN, 2, "The Securities Act of 1933 primarily regulates:", ["The secondary trading market", "The issuance of new securities in the primary market", "The registration of exchanges", "Investment adviser conduct"], 1, "The Securities Act of 1933 — the 'paper act' — governs new issues in the primary market, requiring registration and prospectus delivery. The Securities Exchange Act of 1934 governs the secondary market."),
  q("sm-rg2", RG, RGN, 2, "The federal law that created the Securities and Exchange Commission (SEC) is the:", ["Securities Act of 1933", "Securities Exchange Act of 1934", "Investment Company Act of 1940", "Trust Indenture Act of 1939"], 1, "The Securities Exchange Act of 1934 created the SEC and regulates the secondary market, exchanges, broker-dealers, and practices such as insider trading and manipulation."),
  q("sm-rg3", RG, RGN, 3, "To register an individual as a representative, a member firm files a:", ["Form U5", "Form U4", "Form BD", "Form ADV"], 1, "Firms register a representative by filing Form U4. Form U5 is filed upon termination; Form BD registers the broker-dealer; Form ADV is for investment advisers."),
  q("sm-rg4", RG, RGN, 3, "The Securities Investor Protection Corporation (SIPC) protects a customer against:", ["Losses from a decline in the market value of securities", "The failure of a broker-dealer, up to $500,000 (including up to $250,000 cash)", "Poor investment advice", "Issuer bankruptcy of an individual stock"], 1, "SIPC protects customers if a broker-dealer fails, covering up to $500,000 per customer, of which up to $250,000 may be cash. It does NOT protect against ordinary market losses or bad advice."),
  q("sm-rg5", RG, RGN, 3, "A retail communication distributed to more than 25 retail investors within 30 days generally must be:", ["Filed with the SEC before use", "Approved by a registered principal before first use", "Sent only to accredited investors", "Reviewed by the customer's attorney"], 1, "Retail communications generally require a registered principal's approval before first use (with limited exceptions). 'Correspondence' is written communication to 25 or fewer retail investors in a 30-day period."),
  q("sm-rg6", RG, RGN, 2, "FINRA's continuing education requirement consists of:", ["A Regulatory Element and a Firm Element", "Only an annual exam", "A college course requirement", "A state ethics filing"], 0, "FINRA continuing education has two parts: the Regulatory Element (content from FINRA on compliance and regulatory topics) and the Firm Element (an annual training plan the firm develops for its covered persons)."),
  q("sm-rg7", RG, RGN, 2, "A member of the public can research the background and disciplinary history of a registered representative using:", ["The SEC's EDGAR system", "FINRA BrokerCheck", "The MSRB's EMMA system", "The firm's internal records only"], 1, "FINRA BrokerCheck is the free public tool for researching the employment history, licenses, and disciplinary records of registered representatives and firms. EDGAR holds corporate filings; EMMA holds municipal disclosures."),
];

// ------------------------------------------------------------------
// The full 75-question sit-down exam, in blueprint order.
export const SIE_MOCK_FULL: Question[] = [...SEC1, ...SEC2, ...SEC3, ...SEC4];

// A 15-question, blueprint-weighted readiness sample (≈2 CM, 7 products,
// 5 trading/accounts, 1 regulatory) drawn from the pool.
export const SIE_MOCK_QUICK: Question[] = [
  SEC1[0], SEC1[10],
  SEC2[0], SEC2[6], SEC2[10], SEC2[17], SEC2[23], SEC2[26], SEC2[30],
  SEC3[3], SEC3[8], SEC3[13], SEC3[15], SEC3[18],
  SEC4[3],
];

// Flip to false to hide the full mock while it's being expanded.
export const SIE_FULL_READY = true;

